#!/usr/bin/env python3
"""Render text/images into predeclared content zones.

The script intentionally draws no new frames or cards. It only places content
inside rectangles defined by layout JSON and emits a debug overlay/report.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass
from typing import Any

from PIL import Image, ImageDraw, ImageFont


DEFAULT_FONTS = [
    "/System/Library/Fonts/Supplemental/Arial Unicode.ttf",
    "/System/Library/Fonts/Supplemental/Arial.ttf",
    "/Library/Fonts/Arial Unicode.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
]


@dataclass
class FitResult:
    ok: bool
    font_size: int | None
    lines: list[str]
    bbox: tuple[int, int, int, int] | None
    reason: str | None = None


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--input", help="Base image generated by the image model")
    p.add_argument("--layout", required=True, help="Layout JSON with content zones")
    p.add_argument("--output", help="Final composited image")
    p.add_argument("--debug-output", help="Base/final image with zone overlay")
    p.add_argument("--guide-output", help="Pre-generation blank zone guide")
    p.add_argument("--report", help="JSON fit report")
    return p.parse_args()


def load_json(path: str) -> dict[str, Any]:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def color(value: str | None, default: str = "#ffffff", alpha: int = 255) -> tuple[int, int, int, int]:
    raw = (value or default).strip()
    if raw.startswith("#"):
        raw = raw[1:]
    if len(raw) == 3:
        raw = "".join(ch * 2 for ch in raw)
    if len(raw) == 6:
        return (int(raw[0:2], 16), int(raw[2:4], 16), int(raw[4:6], 16), alpha)
    if len(raw) == 8:
        return (int(raw[0:2], 16), int(raw[2:4], 16), int(raw[4:6], 16), int(raw[6:8], 16))
    raise ValueError(f"Unsupported color: {value!r}")


def ensure_parent(path: str | None) -> None:
    if path:
        parent = os.path.dirname(os.path.abspath(path))
        if parent:
            os.makedirs(parent, exist_ok=True)


def merged(defaults: dict[str, Any], zone: dict[str, Any]) -> dict[str, Any]:
    out = dict(defaults)
    out.update(zone)
    return out


def choose_font_path(zone: dict[str, Any]) -> str | None:
    candidates = []
    if zone.get("font"):
        candidates.append(zone["font"])
    candidates.extend(DEFAULT_FONTS)
    for candidate in candidates:
        if candidate and os.path.exists(candidate):
            return candidate
    return None


def load_font(zone: dict[str, Any], size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    path = choose_font_path(zone)
    if path:
        return ImageFont.truetype(path, size=size)
    return ImageFont.load_default()


def text_width(draw: ImageDraw.ImageDraw, text: str, font: ImageFont.ImageFont, stroke_width: int) -> float:
    bbox = draw.textbbox((0, 0), text, font=font, stroke_width=stroke_width)
    return bbox[2] - bbox[0]


def split_long_word(draw: ImageDraw.ImageDraw, word: str, max_width: int, font: ImageFont.ImageFont, stroke_width: int) -> list[str]:
    parts: list[str] = []
    cur = ""
    for ch in word:
        trial = cur + ch
        if cur and text_width(draw, trial, font, stroke_width) > max_width:
            parts.append(cur)
            cur = ch
        else:
            cur = trial
    if cur:
        parts.append(cur)
    return parts or [word]


def wrap_paragraph(draw: ImageDraw.ImageDraw, paragraph: str, max_width: int, font: ImageFont.ImageFont, stroke_width: int) -> list[str]:
    words = paragraph.split()
    if not words:
        return [""]
    lines: list[str] = []
    cur = ""
    for word in words:
        word_parts = [word]
        if text_width(draw, word, font, stroke_width) > max_width:
            word_parts = split_long_word(draw, word, max_width, font, stroke_width)
        for part in word_parts:
            trial = part if not cur else f"{cur} {part}"
            if cur and text_width(draw, trial, font, stroke_width) > max_width:
                lines.append(cur)
                cur = part
            else:
                cur = trial
    if cur:
        lines.append(cur)
    return lines


def wrap_text(draw: ImageDraw.ImageDraw, text: str, max_width: int, font: ImageFont.ImageFont, stroke_width: int) -> list[str]:
    lines: list[str] = []
    for paragraph in text.splitlines() or [""]:
        lines.extend(wrap_paragraph(draw, paragraph, max_width, font, stroke_width))
    return lines


def fit_text(
    draw: ImageDraw.ImageDraw,
    text: str,
    zone: dict[str, Any],
    rect: tuple[int, int, int, int],
) -> FitResult:
    _, _, w, h = rect
    stroke_width = int(zone.get("stroke_width", 0) or 0)
    max_font = int(zone.get("max_font", 64))
    min_font = int(zone.get("min_font", 16))
    line_spacing = float(zone.get("line_spacing", 1.08))

    for size in range(max_font, min_font - 1, -1):
        font = load_font(zone, size)
        spacing = max(0, int(size * (line_spacing - 1.0) + 2))
        lines = wrap_text(draw, text, w, font, stroke_width)
        body = "\n".join(lines)
        bbox = draw.multiline_textbbox((0, 0), body, font=font, spacing=spacing, stroke_width=stroke_width, align=zone.get("align", "center"))
        if bbox[2] - bbox[0] <= w and bbox[3] - bbox[1] <= h:
            return FitResult(True, size, lines, bbox)

    return FitResult(False, None, [], None, f"text does not fit at min_font={min_font}")


def zone_text(zone: dict[str, Any], content: dict[str, Any]) -> str:
    if "text" in zone:
        value = zone["text"]
    elif zone.get("content_key"):
        value = content.get(zone["content_key"], "")
    else:
        value = ""
    value = "" if value is None else str(value)
    if zone.get("uppercase"):
        value = value.upper()
    return value


def draw_zone_content(
    image: Image.Image,
    zone: dict[str, Any],
    content: dict[str, Any],
) -> dict[str, Any]:
    draw = ImageDraw.Draw(image)
    x, y, w, h = (int(zone[k]) for k in ("x", "y", "w", "h"))
    result: dict[str, Any] = {"id": zone.get("id"), "rect": [x, y, w, h], "ok": True}

    if zone.get("image_path"):
        path = zone["image_path"]
        if not os.path.exists(path):
            if zone.get("required", True):
                result.update(ok=False, reason=f"image_path not found: {path}")
            return result
        src = Image.open(path).convert("RGBA")
        src.thumbnail((w, h), Image.Resampling.LANCZOS)
        px = x + (w - src.width) // 2
        py = y + (h - src.height) // 2
        image.alpha_composite(src, (px, py))
        result.update(kind="image", placed=[px, py, src.width, src.height])
        return result

    text = zone_text(zone, content)
    if not text:
        if zone.get("required", True):
            result.update(ok=False, reason="empty required content")
        return result

    fit = fit_text(draw, text, zone, (x, y, w, h))
    if not fit.ok:
        result.update(ok=False, reason=fit.reason)
        return result

    assert fit.font_size is not None and fit.bbox is not None
    font = load_font(zone, fit.font_size)
    stroke_width = int(zone.get("stroke_width", 0) or 0)
    stroke_fill = color(zone.get("stroke_fill"), "#000000") if stroke_width else None
    fill = color(zone.get("color"), "#ffffff")
    line_spacing = float(zone.get("line_spacing", 1.08))
    spacing = max(0, int(fit.font_size * (line_spacing - 1.0) + 2))
    body = "\n".join(fit.lines)
    bbox = fit.bbox
    text_w = bbox[2] - bbox[0]
    text_h = bbox[3] - bbox[1]

    align = zone.get("align", "center")
    valign = zone.get("valign", "middle")
    if align == "left":
        tx = x - bbox[0]
    elif align == "right":
        tx = x + w - text_w - bbox[0]
    else:
        tx = x + (w - text_w) / 2 - bbox[0]

    if valign == "top":
        ty = y - bbox[1]
    elif valign == "bottom":
        ty = y + h - text_h - bbox[1]
    else:
        ty = y + (h - text_h) / 2 - bbox[1]

    draw.multiline_text(
        (tx, ty),
        body,
        font=font,
        fill=fill,
        spacing=spacing,
        align=align,
        stroke_width=stroke_width,
        stroke_fill=stroke_fill,
    )
    result.update(
        kind="text",
        font_size=fit.font_size,
        lines=fit.lines,
        text_bbox=[round(tx + bbox[0]), round(ty + bbox[1]), round(text_w), round(text_h)],
    )
    return result


def draw_debug(base: Image.Image, layout: dict[str, Any], report: list[dict[str, Any]]) -> Image.Image:
    out = base.convert("RGBA")
    overlay = Image.new("RGBA", out.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)
    by_id = {str(item.get("id")): item for item in report}
    for raw_zone in layout.get("zones", []):
        zone = merged(layout.get("defaults", {}), raw_zone)
        x, y, w, h = (int(zone[k]) for k in ("x", "y", "w", "h"))
        ok = by_id.get(str(zone.get("id")), {}).get("ok", True)
        outline = color(zone.get("debug_color"), "#36D399" if ok else "#FF3366", 230)
        fill = (outline[0], outline[1], outline[2], 38)
        draw.rectangle([x, y, x + w, y + h], fill=fill, outline=outline, width=3)
        label = str(zone.get("id", "zone"))
        font = load_font({"font": zone.get("font")}, 18)
        raw_bbox = draw.textbbox((0, 0), label, font=font, stroke_width=2)
        label_w = raw_bbox[2] - raw_bbox[0]
        label_h = raw_bbox[3] - raw_bbox[1]
        label_x = max(0, min(x + 8, out.width - label_w - 8))
        label_y = y - label_h - 8 if y > label_h + 10 else y + 6
        label_bbox = draw.textbbox((label_x, label_y), label, font=font, stroke_width=2)
        draw.rectangle(label_bbox, fill=(0, 0, 0, 150))
        draw.text((label_x, label_y), label, font=font, fill=outline, stroke_width=2, stroke_fill=(0, 0, 0, 255))
    out.alpha_composite(overlay)
    return out


def blank_guide(layout: dict[str, Any]) -> Image.Image:
    canvas = layout.get("canvas", {})
    w = int(canvas["width"])
    h = int(canvas["height"])
    return Image.new("RGBA", (w, h), (18, 17, 22, 255))


def validate_canvas(image: Image.Image, layout: dict[str, Any]) -> None:
    canvas = layout.get("canvas", {})
    expected = (int(canvas["width"]), int(canvas["height"]))
    if image.size != expected:
        raise ValueError(f"image size {image.size} does not match layout canvas {expected}")


def main() -> int:
    args = parse_args()
    layout = load_json(args.layout)
    zones = layout.get("zones") or []
    if not zones:
        raise ValueError("layout must contain at least one zone")

    if args.input:
        image = Image.open(args.input).convert("RGBA")
    else:
        image = blank_guide(layout)
    validate_canvas(image, layout)

    defaults = layout.get("defaults", {})
    content = layout.get("content", {})
    zone_reports: list[dict[str, Any]] = []

    if args.output:
        final = image.copy()
        for raw_zone in zones:
            zone_reports.append(draw_zone_content(final, merged(defaults, raw_zone), content))
        ensure_parent(args.output)
        final.convert("RGB").save(args.output)
        debug_base = final
    else:
        for raw_zone in zones:
            zone = merged(defaults, raw_zone)
            zone_reports.append({"id": zone.get("id"), "rect": [zone.get("x"), zone.get("y"), zone.get("w"), zone.get("h")], "ok": True, "kind": "guide"})
        debug_base = image

    ok = all(item.get("ok", False) for item in zone_reports)

    if args.debug_output:
        ensure_parent(args.debug_output)
        draw_debug(debug_base, layout, zone_reports).convert("RGB").save(args.debug_output)
    if args.guide_output:
        ensure_parent(args.guide_output)
        draw_debug(blank_guide(layout), layout, zone_reports).convert("RGB").save(args.guide_output)
    if args.report:
        ensure_parent(args.report)
        with open(args.report, "w", encoding="utf-8") as f:
            json.dump({"ok": ok, "zones": zone_reports}, f, ensure_ascii=False, indent=2)

    if not ok:
        sys.stderr.write("One or more required content zones failed. See report/debug overlay.\n")
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
