extends RefCounted

# SCRUM-198: character, stat and class identity data. ProgressionData keeps compatibility aliases.

const STAT_NAMES := {
	"strength": "Сила",
	"agility": "Ловкость",
	"intelligence": "Интеллект",
	"perception": "Восприятие",
	"energy": "Энергия",
	"knowledge": "Знание",
	"endurance": "Выносливость",
	"leadership": "Лидерство",
}

const BASE_STATS := {
	"berserk": {
		"strength": 10.0,
		"agility": 5.0,
		"intelligence": 2.0,
		"perception": 5.0,
		"energy": 4.0,
		"knowledge": 4.0,
		"endurance": 7.0,
		"leadership": 3.0,
	},
	"soldier": {
		"strength": 7.0,
		"agility": 6.0,
		"intelligence": 2.0,
		"perception": 8.0,
		"energy": 4.0,
		"knowledge": 5.0,
		"endurance": 6.0,
		"leadership": 5.0,
	},
	"thief": {
		"strength": 5.0,
		"agility": 9.0,
		"intelligence": 3.0,
		"perception": 8.0,
		"energy": 5.0,
		"knowledge": 4.0,
		"endurance": 4.0,
		"leadership": 5.0,
	},
	"elementalist": {
		"strength": 2.0,
		"agility": 4.0,
		"intelligence": 9.0,
		"perception": 7.0,
		"energy": 8.0,
		"knowledge": 6.0,
		"endurance": 3.0,
		"leadership": 5.0,
	},
	"sniper": {
		"strength": 6.0,
		"agility": 8.0,
		"intelligence": 2.0,
		"perception": 10.0,
		"energy": 3.0,
		"knowledge": 3.0,
		"endurance": 7.0,
		"leadership": 1.0,
	},
	"priest": {
		"strength": 2.0,
		"agility": 4.0,
		"intelligence": 8.0,
		"perception": 6.0,
		"energy": 7.0,
		"knowledge": 9.0,
		"endurance": 5.0,
		"leadership": 6.0,
	},
	"biologist": {
		"strength": 2.0,
		"agility": 5.0,
		"intelligence": 8.0,
		"perception": 7.0,
		"energy": 6.0,
		"knowledge": 10.0,
		"endurance": 4.0,
		"leadership": 4.0,
	},
	"robot": {
		"strength": 8.0,
		"agility": 3.0,
		"intelligence": 5.0,
		"perception": 5.0,
		"energy": 7.0,
		"knowledge": 4.0,
		"endurance": 10.0,
		"leadership": 4.0,
	},
	"engineer": {
		"strength": 4.0,
		"agility": 5.0,
		"intelligence": 7.0,
		"perception": 6.0,
		"energy": 6.0,
		"knowledge": 6.0,
		"endurance": 5.0,
		"leadership": 10.0,
	},
	"dark_mage": {
		"strength": 2.0,
		"agility": 3.0,
		"intelligence": 10.0,
		"perception": 5.0,
		"energy": 7.0,
		"knowledge": 6.0,
		"endurance": 3.0,  # SCRUM-783: 2.0→3.0 — поднять пол выживаемости (EHP ~34.6→~50,
		# уровень aoe-стекла elementalist/chemist). Остаётся самым хрупким aoe-классом, но
		# не умирает от одного касания. survival-tier/damage-таргеты НЕ затронуты (отдельный label).
		"leadership": 5.0,
	},
	"guitarist": {
		"strength": 4.0,
		"agility": 6.0,
		"intelligence": 4.0,
		"perception": 7.0,
		"energy": 6.0,
		"knowledge": 5.0,
		"endurance": 4.0,
		"leadership": 7.0,
	},
	"assassin": {"strength": 6.0, "agility": 10.0, "intelligence": 2.0, "perception": 6.0, "energy": 3.0, "knowledge": 4.0, "endurance": 5.0, "leadership": 4.0},
	"ranger": {"strength": 7.0, "agility": 7.0, "intelligence": 2.0, "perception": 9.0, "energy": 4.0, "knowledge": 4.0, "endurance": 4.0, "leadership": 3.0},
	"doctor": {"strength": 2.0, "agility": 4.0, "intelligence": 8.0, "perception": 5.0, "energy": 6.0, "knowledge": 8.0, "endurance": 5.0, "leadership": 2.0},
	"chemist": {"strength": 2.0, "agility": 4.0, "intelligence": 9.0, "perception": 6.0, "energy": 7.0, "knowledge": 7.0, "endurance": 3.0, "leadership": 2.0},
	"knight": {"strength": 8.0, "agility": 3.0, "intelligence": 2.0, "perception": 4.0, "energy": 3.0, "knowledge": 4.0, "endurance": 10.0, "leadership": 6.0},
	"druid": {"strength": 3.0, "agility": 4.0, "intelligence": 4.0, "perception": 7.0, "energy": 6.0, "knowledge": 5.0, "endurance": 5.0, "leadership": 9.0},
}

const CHARACTER_CONFIGS := {
	# SCRUM-887: описания = что ожидать от геймплея (дистанция, темп, риск, за
	# счет чего убивает/выживает); сильные/слабые — только правда по механикам.
	"berserk": {
		"id": "berserk",
		"title": "Берсерк",
		"description": "Ближний рубака: тяжелые двуручные замахи кладут толпу вокруг. Живет в гуще боя — риск велик, но и запас крови огромен.",
		"strengths": "тяжелый урон по толпе, большой запас здоровья, широкие дуги ударов.",
		"weaknesses": "должен подойти вплотную, дальних ответов нет.",
		"sprite_path": "res://assets/sprites/characters/full_frame/berserk_pixellab/berserk_idle_south.png",
	},
	"soldier": {
		"id": "soldier",
		"title": "Солдат",
		"description": "Стрелок средней дистанции: держит строй, кладет залпы по линии и рвет скопления гранатами. Ровный темп без лишнего риска.",
		"strengths": "ровный урон с дистанции, залпы по линии, гранаты по скоплениям, штыковая оборона.",
		"weaknesses": "нужна линия огня, по боссу залпы слабее.",
		"sprite_path": "res://assets/sprites/characters/full_frame/soldier_pixellab/soldier_idle_south.png",
	},
	"thief": {
		"id": "thief",
		"title": "Вор",
		"description": "Быстрый плут: монеты скачут рикошетом по толпе, тень бьет в спину, дым укрывает. Хрупок, но верток — и по пути набивает кошель.",
		"strengths": "высокий темп и криты, удары в спину, рикошеты по толпе, добыча золота.",
		"weaknesses": "мало здоровья, ошибку вплотную не прощает.",
		"sprite_path": "res://assets/sprites/characters/full_frame/thief_pixellab/thief_idle_south.png",
	},
	"elementalist": {
		"id": "elementalist",
		"title": "Элементалист",
		"description": "Маг зон: орбиты стихий жгут вокруг, разломы и метеоры накрывают области. Смертоносен, пока враг в его зонах, — и хрупок вне их.",
		"strengths": "взрывной урон по области, контроль зон, орбиты вокруг себя.",
		"weaknesses": "хрупкий, требует позиции и расчета.",
		"sprite_path": "res://assets/sprites/characters/full_frame/elementalist_pixellab/elementalist_idle_south.png",
	},
	"sniper": {
		"id": "sniper",
		"title": "Снайпер",
		"description": "Дальнобойный ликвидатор: выцеливает жертву, пробивает ее насквозь и размечает зоны смерти. Смертелен издали, беззащитен вплотную.",
		"strengths": "огромная дальность, тяжелые точные выстрелы, криты, фокус элит.",
		"weaknesses": "слаб против толпы вплотную.",
		"sprite_path": "res://assets/sprites/characters/full_frame/sniper_pixellab/sniper_idle_south.png",
	},
	"priest": {
		"id": "priest",
		"title": "Священник",
		"description": "Боевой пастырь: печати и молитвы жгут нечисть на средней дистанции, а часть причиненной боли возвращается ему лечением.",
		"strengths": "постоянное самолечение, защитные волны, цепные молитвы, ровный урон.",
		"weaknesses": "нет взрывного урона по одной цели.",
		"sprite_path": "res://assets/sprites/characters/full_frame/priest_pixellab/priest_idle_south.png",
	},
	"biologist": {
		"id": "biologist",
		"title": "Биолог",
		"description": "Испытатель плоти: засевает врагов спорами, берет образцы и вяжет их в зараженные сети. Урон тикает и расползается по толпе.",
		"strengths": "урон со временем, цепные заражения, давление по группам.",
		"weaknesses": "медленный разгон, нужны цели для цепей.",
		"sprite_path": "res://assets/sprites/characters/full_frame/biologist_pixellab/biologist_idle_south.png",
	},
	"robot": {
		"id": "robot",
		"title": "Робот",
		"description": "Ходячая крепость: стягивает врагов магнитом, давит прессом и жжет выбросами реактора. Медлителен, зато почти неубиваем.",
		"strengths": "огромная живучесть, стягивание врагов, контроль толпы, ровный урон.",
		"weaknesses": "медлителен, любит верную позицию.",
		"sprite_path": "res://assets/sprites/characters/full_frame/robot_pixellab/robot_idle_south.png",
	},
	"engineer": {
		"id": "engineer",
		"title": "Инженер",
		"description": "Мастер расстановки: турели бьют сами, дроны чинят, мины стерегут подходы. Побеждает подготовкой поля, а не собственной рукой.",
		"strengths": "самостоятельные турели, ремонт на ходу, минный контроль подходов.",
		"weaknesses": "слаб, пока устройства не расставлены.",
		"sprite_path": "res://assets/sprites/characters/full_frame/engineer_pixellab/engineer_idle_south.png",
	},
	"dark_mage": {
		"id": "dark_mage",
		"title": "Темный маг",
		"description": "Стеклянная пушка: книги, лучи и проклятия выжигают целые области издали. Убивает раньше, чем до него дойдут, — иначе умрет сам.",
		"strengths": "мощный урон по области, пробивающие лучи, проклятия со временем.",
		"weaknesses": "самый хрупкий, вблизи обречен.",
		"sprite_path": "res://assets/sprites/characters/full_frame/dark_mage_pixellab/dark_mage_idle_south.png",
	},
	"guitarist": {
		"id": "guitarist",
		"title": "Гитарист",
		"description": "Заклинатель звука: волны бьют вперед, бас расталкивает кольцом, усилители гремят сами. Держит толпу на расстоянии рева.",
		"strengths": "отталкивание толпы, волны по области, усилители-помощники, темп.",
		"weaknesses": "по боссам заметно слабее.",
		"sprite_path": "res://assets/sprites/characters/full_frame/guitarist_pixellab/guitarist_idle_south.png",
	},
	"assassin": {
		"id": "assassin", "title": "Ассасин",
		"description": "Хладнокровный резчик: чакрамы режут коридор туда и обратно, кинжалы шинкуют в упор, струна душит ядом. Живет критами и уворотом.",
		"strengths": "частые криты, высокий темп ударов, уворот, яд.",
		"weaknesses": "мало здоровья, промах стоит крови.",
		"sprite_path": "res://assets/sprites/characters/full_frame/assassin_pixellab/assassin_idle_south.png",
	},
	"ranger": {
		"id": "ranger", "title": "Рейнджер",
		"description": "Терпеливый охотник: стоит на месте — выстрел заряжается и пробивает ряд насквозь. Капканы стерегут тех, кто подберется.",
		"strengths": "дальние пробивающие выстрелы, награда за стойку, капканы.",
		"weaknesses": "вблизи и на бегу заметно слабее.",
		"sprite_path": "res://assets/sprites/characters/full_frame/ranger_pixellab/ranger_idle_south.png",
	},
	"doctor": {
		"id": "doctor", "title": "Доктор",
		"description": "Врач без жалости: тянет жизнь из пациентов зельем, чумой и пилой. Каждая рана врага — его лекарство; не бьет — не лечится.",
		"strengths": "лечение собственным уроном, яд, живучесть в затяжном бою.",
		"weaknesses": "низкий разовый урон, без ударов не лечится.",
		"sprite_path": "res://assets/sprites/characters/full_frame/doctor_pixellab/doctor_idle_south.png",
	},
	"chemist": {
		"id": "chemist", "title": "Химик",
		"description": "Алхимик выжженной земли: взрывы, кислотные лужи и ядовитые облака превращают арену в отраву. Хрупок — пусть работает химия.",
		"strengths": "едкие зоны, урон со временем, взрывы по области, гомункул-помощник.",
		"weaknesses": "хрупкий, урону нужно время.",
		"sprite_path": "res://assets/sprites/characters/full_frame/chemist_pixellab/chemist_idle_south.png",
	},
	"knight": {
		"id": "knight", "title": "Рыцарь",
		"description": "Латная стена: держит удар щитом, отвечает контрударом и достает копьем через ряд. Медленный, зато почти не продавливается.",
		"strengths": "отличная защита и здоровье, блок с контрударом, контроль строя.",
		"weaknesses": "медленный, догоняет плохо.",
		"sprite_path": "res://assets/sprites/characters/full_frame/knight_pixellab/knight_idle_south.png",
	},
	"druid": {
		"id": "druid", "title": "Друид",
		"description": "Пастырь дикой стаи: звери рвут добычу по его слову, тернии и тотемы стерегут землю. Сам слаб — сила в своре и корнях.",
		"strengths": "стая зверей, терновые зоны, тотемы поддержки.",
		"weaknesses": "без стаи почти беспомощен.",
		"sprite_path": "res://assets/sprites/characters/full_frame/druid_pixellab/druid_idle_south.png",
	},
}

const ULTIMATE_CONFIGS := {
	"berserk": {"title": "Неистовство", "description": "На несколько секунд ускоряется и каждый удар поднимает эхо-волну.", "duration": 5.5, "radius": 180.0, "damage": 0.75, "damage_charge_rate": 0.030, "taken_charge_rate": 1.35, "boss_cap": 0.10},
	"soldier": {"title": "Приказ: Огонь", "description": "Серия прицельных залпов по ближайшим целям; сильнее по плотной толпе, но ограничена по боссу.", "duration": 0.0, "radius": 560.0, "damage": 1.08, "target_count": 9, "damage_charge_rate": 0.033, "taken_charge_rate": 1.12, "boss_cap": 0.09},
	"thief": {"title": "Большой Куш", "description": "Мгновенный налет по ближайшим целям: урон, золотые нити и небольшой денежный выигрыш.", "duration": 0.0, "radius": 500.0, "damage": 1.02, "target_count": 8, "damage_charge_rate": 0.036, "taken_charge_rate": 1.00, "boss_cap": 0.08},
	"elementalist": {"title": "Стихийная Сверхнова", "description": "Сверхнова четырех стихий взрывается вокруг героя и оставляет вторичные вспышки по ближайшим целям.", "duration": 0.0, "radius": 430.0, "damage": 1.18, "target_count": 6, "damage_charge_rate": 0.035, "taken_charge_rate": 1.04, "boss_cap": 0.10},
	"sniper": {"title": "Последний Выстрел", "description": "Снайпер отмечает опасные цели и выпускает серию смертельных дальних попаданий.", "duration": 0.0, "radius": 760.0, "damage": 1.35, "target_count": 5, "damage_charge_rate": 0.034, "taken_charge_rate": 0.95, "boss_cap": 0.10},
	"priest": {"title": "Хор Искупления", "description": "Священная волна поражает врагов вокруг и превращает часть урона в лечение.", "duration": 0.0, "radius": 410.0, "damage": 1.05, "target_count": 8, "heal_ratio": 0.45, "damage_charge_rate": 0.031, "taken_charge_rate": 1.22, "boss_cap": 0.08},
	"biologist": {"title": "Пробуждение Колонии", "description": "Биолог запускает рост живой колонии: несколько биоимпульсов поражают ближайших врагов и оставляют слабый реген.", "duration": 0.0, "radius": 440.0, "damage": 1.10, "target_count": 9, "heal_ratio": 0.18, "damage_charge_rate": 0.033, "taken_charge_rate": 1.05, "boss_cap": 0.09},
	"robot": {"title": "Аварийная Перегрузка", "description": "Робот включает аварийный контур: получает временное поглощение, выпускает ударную волну и несколько раз прожигает ближайших врагов.", "duration": 4.5, "radius": 380.0, "damage": 0.78, "target_count": 8, "damage_charge_rate": 0.030, "taken_charge_rate": 1.55, "boss_cap": 0.08},
	"engineer": {"title": "Аварийная Мастерская", "description": "Инженер быстро разворачивает временную сеть устройств: лучи, ремонт и взрывные узлы вокруг себя.", "duration": 4.2, "radius": 430.0, "damage": 0.92, "target_count": 9, "heal_ratio": 0.12, "damage_charge_rate": 0.031, "taken_charge_rate": 1.18, "boss_cap": 0.08},
	"dark_mage": {"title": "Темная буря", "description": "Вихрь темной магии проклинает всех врагов вокруг.", "duration": 0.0, "radius": 360.0, "damage": 1.35, "damage_charge_rate": 0.034, "taken_charge_rate": 1.05, "boss_cap": 0.11},
	"guitarist": {"title": "Соло", "description": "Гигантская звуковая волна отбрасывает и глушит толпу.", "duration": 0.0, "radius": 430.0, "damage": 1.15, "damage_charge_rate": 0.033, "taken_charge_rate": 1.10, "boss_cap": 0.09},
	"assassin": {"title": "Танец клинков", "description": "Серия мгновенных рывков-ударов по ближайшим целям.", "duration": 0.0, "radius": 520.0, "damage": 1.05, "target_count": 7, "damage_charge_rate": 0.036, "taken_charge_rate": 1.05, "boss_cap": 0.08},
	"ranger": {"title": "Лунный залп", "description": "Дождь болтов поражает большую область вокруг героя.", "duration": 0.0, "radius": 480.0, "damage": 1.18, "target_count": 14, "damage_charge_rate": 0.034, "taken_charge_rate": 1.0, "boss_cap": 0.09},
	"doctor": {"title": "Переливание", "description": "Массовый drain врагов вокруг; избыток лечения становится щитом-поглощением.", "duration": 0.0, "radius": 360.0, "damage": 0.95, "damage_charge_rate": 0.032, "taken_charge_rate": 1.25, "boss_cap": 0.08},
	"chemist": {"title": "Цепная реакция", "description": "Алхимический каскад детонирует ближайшие зоны и врагов.", "duration": 0.0, "radius": 420.0, "damage": 1.25, "damage_charge_rate": 0.034, "taken_charge_rate": 1.05, "boss_cap": 0.10},
	"knight": {"title": "Бастион", "description": "Короткая непробиваемость, таунт давления и усиленная контратака.", "duration": 5.0, "radius": 260.0, "damage": 0.70, "damage_charge_rate": 0.029, "taken_charge_rate": 1.55, "boss_cap": 0.07},
	"druid": {"title": "Зов стаи", "description": "Временно призывает сверхлимитную стаю союзников.", "duration": 6.0, "radius": 260.0, "damage": 0.80, "target_count": 4, "damage_charge_rate": 0.031, "taken_charge_rate": 1.10, "boss_cap": 0.08},
}

const CLASS_MECHANIC_IDENTITIES := {
	"berserk": {
		"main_attribute": "strength",
		"identity_title": "Телесный напор",
			"summary": "Сила наливает двуручные замахи весом: чем она выше, тем шире и смертоноснее каждый удар по толпе.",
			"mechanic_tags": ["melee_geometry", "frontal_pressure", "crowd_control", "echo_weapon"],
			"weapon_identities": {
				"sword": "длинный узкий сектор 100 градусов для позиционирования",
				"axe": "широкий сектор 180 градусов для чистки толпы рядом",
				"hammer": "центральный круговой slam радиуса 150 с ростом от Radius",
			},
	},
	"soldier": {
		"main_attribute": "perception",
		"identity_title": "Тактическая линия огня",
		"summary": "Восприятие задает линию огня: солдат видит дальше, бьет точнее и держит позицию, пока враг не дрогнет.",
		"mechanic_tags": ["line_control", "suppression", "telegraphed_explosive", "brace"],
		"weapon_identities": {
			"soldier_rifle": "подавляющий burst по линии",
			"soldier_grenade": "задержанная граната с читаемой зоной",
			"soldier_bayonet": "оборонительная штыковая стойка",
		},
	},
	"thief": {
		"main_attribute": "agility",
		"identity_title": "Уловка и темп",
		"summary": "Ловкость — его монета: чем быстрее руки, тем чаще криты, увороты и трюки, на которые враг не успевает ответить.",
		"mechanic_tags": ["mobility", "ricochet", "backstab", "smoke_evasion"],
		"weapon_identities": {
			"thief_coin_pouch": "золотой рикошет по нескольким целям",
			"thief_shadow_cloak": "рывок/удар в уязвимое окно",
			"thief_smoke_bomb": "дымовая зона контроля и уклонения",
		},
	},
	"elementalist": {
		"main_attribute": "intelligence",
		"identity_title": "Стихийная формула",
		"summary": "Интеллект складывает стихии в формулы: чем он выше, тем злее горят орбиты, разломы и метеорные зоны.",
		"mechanic_tags": ["element_cycle", "orbit", "rift", "area_combo"],
		"weapon_identities": {
			"elementalist_orb_ring": "вращающиеся стихийные орбиты",
			"elementalist_prism_focus": "разлом-призма с направленным контролем",
			"elementalist_meteor_core": "осколочный метеорный обстрел",
		},
	},
	"sniper": {
		"main_attribute": "perception",
		"identity_title": "Точная ликвидация",
		"summary": "Восприятие — его прицел: чем зорче глаз, тем дальше бьет винтовка и тем шире зона, где врагу не выжить.",
		"mechanic_tags": ["precision", "marking", "long_range", "kill_zone"],
		"weapon_identities": {
			"sniper_deadeye_rifle": "дальний lockshot по приоритетной цели",
			"sniper_spotter_scope": "зона смерти, наказывающая проходящих врагов",
			"sniper_shatter_rounds": "разделяющийся выстрел по нескольким линиям",
		},
	},
	"priest": {
		"main_attribute": "knowledge",
		"identity_title": "Священная формула",
		"summary": "Знание — его псалтырь: чем оно глубже, тем крепче печати, злее кара и щедрее лечение от каждого удара.",
		"mechanic_tags": ["sanctify", "ward", "heal_conversion", "holy_chain"],
		"weapon_identities": {
			"priest_reliquary": "освящение зоны вокруг цели",
			"priest_censer": "ward-пульсы защиты и урона",
			"priest_chime": "цепная молитва между врагами",
		},
	},
	"biologist": {
		"main_attribute": "knowledge",
		"identity_title": "Биореакция",
		"summary": "Знание превращает врага в подопытного: чем оно выше, тем злее споры, точнее анализ и живучее зараза.",
		"mechanic_tags": ["sample_analysis", "spores", "biomass", "adaptive_dot"],
		"weapon_identities": {
			"biologist_spore_lens": "spore bloom зона с тиками",
			"biologist_sample_injector": "sample dart для анализа и фокус-урона",
			"biologist_symbiote_seed": "симбиотическая web-сетка контроля",
		},
	},
	"robot": {
		"main_attribute": "endurance",
		"identity_title": "Бронеконтур",
		"summary": "Выносливость питает броню и реактор: чем крепче корпус, тем дольше машина держит натиск и давит в ответ.",
		"mechanic_tags": ["armor_loop", "magnet", "compression", "reactor_heat"],
		"weapon_identities": {
			"robot_magnetic_anchor": "магнитный якорь, стягивающий цель",
			"robot_hydraulic_press": "гидравлическая линия компрессии",
			"robot_reactor_core": "реакторная зона перегрева",
		},
	},
	"engineer": {
		"main_attribute": "leadership",
		"identity_title": "Мастерская приказов",
		"summary": "Лидерство командует железом: чем тверже рука мастера, тем больше турелей, дронов и мин служат ему разом.",
		"mechanic_tags": ["deployable_network", "device_command", "repair_support", "minefield"],
		"weapon_identities": {
			"engineer_sentry_wrench": "развёртка стационарных турелей и удержание зоны",
			"engineer_repair_drone": "repair drone с поддержкой",
			"engineer_pressure_mines": "pressure mines для контроля маршрутов",
		},
	},
	"dark_mage": {
		"main_attribute": "intelligence",
		"identity_title": "Темная формула",
		"summary": "Интеллект кормит тьму: чем острее ум, тем шире области распада и глубже вгрызаются проклятия.",
		"mechanic_tags": ["curse", "beam", "dot", "aoe_burst"],
		"weapon_identities": {
			"dark_book": "двойной AoE projectile",
			"cursed_skull": "homing curse с DoT",
			"dark_wand": "двойной pierce beam",
		},
	},
	"guitarist": {
		"main_attribute": "leadership",
		"identity_title": "Сценический контроль",
		"summary": "Лидерство собирает толпу на его концерт: чем громче имя, тем тяжелее волны и чаще гремят усилители.",
		"mechanic_tags": ["rhythm", "knockback", "aura", "deploy_amp"],
		"weapon_identities": {
			"electric_guitar": "направленная звуковая волна",
			"bass_guitar": "частый круговой бас-пульс",
			"sound_amp": "deploy-усилитель с самостоятельными пульсами",
		},
	},
	"assassin": {
		"main_attribute": "agility",
		"identity_title": "Критический танец",
		"summary": "Ловкость — его клинок: чем быстрее руки, тем плотнее ложатся криты и тем труднее его задеть.",
		"mechanic_tags": ["crit_window", "boomerang", "flurry", "poison_line", "shadow_burst"],
		"weapon_identities": {
			"chakrams": "boomerang-коридор туда и обратно",
			"shadow_daggers": "короткая stab flurry серия",
			"venom_wire": "ядовитая pierce-линия",
		},
	},
	"ranger": {
		"main_attribute": "perception",
		"identity_title": "Охотничья стойка",
		"summary": "Восприятие — взгляд охотника: чем он острее, тем дальше летит болт и тем глубже пробивает строй.",
		"mechanic_tags": ["stance_charge", "long_range", "trap", "piercing_shot"],
		"weapon_identities": {
			"moon_crossbow": "заряжаемый одиночный piercing shot",
			"storm_longbow": "веер дальних charged beams",
			"hunter_trap": "deploy trap с burst и knockback",
		},
	},
	"doctor": {
		"main_attribute": "knowledge",
		"identity_title": "Клинический drain",
		"summary": "Знание сшивает урон и лечение: чем глубже познания, тем больше чужой боли возвращается к нему здоровьем.",
		"mechanic_tags": ["drain_link", "self_sustain_only", "plague", "surgical_melee"],
		"weapon_identities": {
			"restore_potion": "лечащая drain-связь",
			"plague_syringe": "чумная DoT-связь",
			"bone_saw": "ближняя saw flurry с sustain",
		},
	},
	"chemist": {
		"main_attribute": "intelligence",
		"identity_title": "Алхимическая цепь",
		"summary": "Интеллект смешивает реагенты без промаха: чем яснее расчет, тем злее взрывы и едче кислотные лужи.",
		"mechanic_tags": ["cloud_combo", "acid_pool", "explosion", "homunculus"],
		"weapon_identities": {
			"blast_powder": "взрывная пыль и spark cloud",
			"acid_flask": "кислотный DoT pool",
			"homunculus_vial": "temporary homunculus summon",
		},
	},
	"knight": {
		"main_attribute": "endurance",
		"identity_title": "Щитовая клятва",
		"summary": "Выносливость — его клятва: чем крепче рыцарь, тем тверже блок и тяжелее ответный удар.",
		"mechanic_tags": ["block", "counter", "frontal_control", "tank_pressure"],
		"weapon_identities": {
			"long_spear": "длинный strip-контроль копьем",
			"tower_shield": "shield bash и frontal block",
			"holy_flail": "круговой тяжелый holy control",
		},
	},
	"druid": {
		"main_attribute": "leadership",
		"identity_title": "Командование стаей",
		"summary": "Лидерство — голос леса: чем тверже воля друида, тем больше зверей идет на зов и злее рвет добычу.",
		"mechanic_tags": ["commanded_pets", "briar_zone", "totem", "pack_support"],
		"weapon_identities": {
			"summon_amulet": "commanded pet attack target",
			"briar_staff": "терновая зона контроля",
			"raven_totem": "raven/totem support pulses",
		},
	},
}

const CLASS_DAMAGE_PARAMETER := {
	"berserk": "damage",
	"soldier": "damage",
	"thief": "damage",
	"elementalist": "magic_damage",
	"sniper": "damage",
	"priest": "magic_damage",
	"biologist": "magic_damage",
	"robot": "damage",
	"engineer": "damage",
	"dark_mage": "magic_damage",
	"guitarist": "sound_wave_damage",
	"assassin": "damage",
	"ranger": "damage",
	"knight": "damage",
	"doctor": "magic_damage",
	"chemist": "magic_damage",
	"druid": "sound_wave_damage",
}

const STAT_CLASS_RELEVANCE := {}

const CLASS_INTERPRETATIONS := {
	"berserk": {
		"strength": "Прямо усиливает двуручное оружие.",
		"intelligence": "Почти не влияет на двуручное оружие: физический урон Берсерка остается завязан на Силу.",
		"energy": "Ускоряет темп уникальных срабатываний, но не превращает двуручные удары в магический или звуковой урон.",
		"leadership": "Каждые несколько ударов вызывает призрачное эхо-оружие.",
		"magic_damage": "Не усиливает двуручные физические удары Берсерка; полезность минимальна без отдельного магического источника.",
		"sound_wave_damage": "Не усиливает двуручные физические удары Берсерка; полезность минимальна без отдельного звукового источника.",
		"dot_damage": "Добавляет малое кровотечение к ударам.",
		"summon_amount": "Повышает частоту эхо-оружия.",
	},
	"soldier": {
		"strength": "Усиливает залпы, штык и вес гранат.",
		"intelligence": "Добавляет рунический воспламенитель к гранатам и выстрелам.",
		"energy": "Ускоряет тактические циклы: фитиль, залп и готовность ульты.",
		"knowledge": "Добавляет горение/кровотечение к пораженным целям.",
		"leadership": "Командный клич периодически вызывает эхо-залп строя.",
		"magic_damage": "Работает как зачарованный порох и руническая осколочная искра.",
		"sound_wave_damage": "Работает как команда строя: ближний боевой окрик отталкивает толпу.",
		"dot_damage": "Добавляет малый burn/bleed от пороха и штыка.",
		"summon_amount": "Повышает частоту эхо-залпов и поддержку строя.",
	},
	"thief": {
		"strength": "Добавляет вес backstab-ударам и рикошетам.",
		"agility": "Главный стат: ускоряет темп уловок, крит и выживание через движение.",
		"intelligence": "Зачаровывает дым и монеты теневой искрой.",
		"perception": "Расширяет цепь рикошета, дальность захода и зону дыма.",
		"energy": "Быстрее заряжает Большой Куш и снижает темп провалов.",
		"knowledge": "Добавляет яд/кровотечение к скрытым ударам.",
		"endurance": "Компенсирует низкое HP через устойчивость к ошибкам.",
		"leadership": "Подкупленная тень периодически повторяет удар.",
		"magic_damage": "Работает как теневое зачарование монет и клинков.",
		"sound_wave_damage": "Работает как отвлекающий свист: ближний контроль пространства.",
		"dot_damage": "Добавляет малый яд/bleed к backstab и дыму.",
		"summon_amount": "Учащает подкупленные эхо-удары.",
	},
	"elementalist": {
		"strength": "Утяжеляет метеоры и усиливает knockback от стихийных ударов.",
		"agility": "Ускоряет цикл переключения стихий, движение и шанс крита.",
		"intelligence": "Главный стат: усиливает магический урон всех стихий.",
		"perception": "Расширяет разломы, орбиты и точность выбора зоны.",
		"energy": "Ускоряет заряд Сверхновы и питает длительность стихийных паттернов.",
		"knowledge": "Усиливает burn/frost-like DoT от остаточных вспышек.",
		"endurance": "Компенсирует хрупкость защитой и HP.",
		"leadership": "Фамильяр-искра периодически повторяет малую стихийную вспышку.",
		"damage": "Работает как физический импульс метеорных осколков.",
		"sound_wave_damage": "Работает как громовой хлопок после стихийного удара.",
		"dot_damage": "Добавляет малые burn/frost тики к зонам.",
		"summon_amount": "Учащает фамильярные эхо-вспышки.",
	},
	"sniper": {
		"strength": "Усиливает отдачу тяжелых патронов и knockback lockshot.",
		"agility": "Ускоряет перезарядку, смену позиции и шанс крита.",
		"intelligence": "Зачаровывает патроны малым arcane splash.",
		"perception": "Главный стат: дальность, точность, радиус kill-zone и pickup.",
		"energy": "Быстрее заряжает Последний Выстрел и стабилизирует прицел.",
		"knowledge": "Добавляет bleed/armor-pierce DoT к marked shots.",
		"endurance": "Позволяет пережить ошибку при игре на дистанции.",
		"leadership": "Корректировщик периодически повторяет малый прицельный выстрел.",
		"magic_damage": "Работает как зачарованный наконечник пули.",
		"sound_wave_damage": "Работает как оглушающий дульный хлопок вблизи.",
		"dot_damage": "Добавляет кровотечение к lockshot и split-round.",
		"summon_amount": "Учащает корректировочные эхо-выстрелы.",
	},
	"priest": {
		"strength": "Придает вес кадилу и усиливает knockback священных волн.",
		"agility": "Ускоряет чтение молитв, движение и шанс крита.",
		"intelligence": "Усиливает священный магический урон печатей и молитв.",
		"perception": "Расширяет зоны печатей, дальность реликвария и радиус подбора.",
		"energy": "Быстрее заряжает Хор Искупления и поддерживает частые благословения.",
		"knowledge": "Главный стат: усиливает священные формулы, DoT-покаяние и эффективность лечения.",
		"endurance": "Дает HP/защиту, чтобы удерживать ближнюю ward-зону.",
		"leadership": "Приходская поддержка периодически повторяет малую молитву.",
		"damage": "Работает как физический импульс кадила и реликвария.",
		"sound_wave_damage": "Работает как церковный звон: ближний отталкивающий клич.",
		"dot_damage": "Добавляет покаянное горение к освященным целям.",
		"summon_amount": "Учащает эхо-молитвы прихожан.",
	},
	"biologist": {
		"strength": "Утяжеляет капсулы и повышает knockback биореакций.",
		"agility": "Ускоряет сбор образцов, смену позиции и шанс крита.",
		"intelligence": "Усиливает магическую биохимию спор и симбионтов.",
		"perception": "Расширяет зоны роста, дальность инъектора и радиус подбора.",
		"energy": "Быстрее заряжает Пробуждение Колонии и ускоряет реакционные циклы.",
		"knowledge": "Главный стат: усиливает анализ образцов, DoT и точность биореакций.",
		"endurance": "Компенсирует хрупкость HP/защитой при игре рядом с зонами.",
		"leadership": "Лабораторный ассистент периодически повторяет малую биореакцию.",
		"damage": "Работает как давление капсул и механический импульс инъектора.",
		"sound_wave_damage": "Работает как биоакустический отпугивающий импульс.",
		"dot_damage": "Усиливает споры, инфекционные тики и остаточную биомассу.",
		"summon_amount": "Учащает ассистентские эхо-реакции без добавления отдельного питомца.",
	},
	"robot": {
		"strength": "Главный стат: усиливает сервоприводы, гидравлику и физический импульс оружия.",
		"agility": "Сокращает инерцию корпуса: быстрее перезарядка, движение и шанс крита.",
		"intelligence": "Улучшает боевой алгоритм и добавляет маготехнический splash.",
		"perception": "Расширяет магнитные зоны, дальность захвата и радиус подбора.",
		"energy": "Питает реактор, быстрее заряжает Перегрузку и ускоряет контуры оружия.",
		"knowledge": "Стабилизирует перегрев: усиливает DoT/реген и снижает цену ошибок.",
		"endurance": "Ключевой защитный стат: HP, броня, поглощение и выдержка под давлением.",
		"leadership": "Автопилотный протокол периодически повторяет малый механический импульс.",
		"magic_damage": "Работает как рунический аккумулятор внутри механизма.",
		"sound_wave_damage": "Работает как сирена давления: ближний отталкивающий выброс.",
		"dot_damage": "Добавляет перегрев/искрение к реакторным и прессовым ударам.",
		"summon_amount": "Учащает эхо-протоколы сервоприводов без отдельного питомца.",
	},
	"engineer": {
		"strength": "Усиливает тяжелые инструменты, мины и отдачу турелей.",
		"agility": "Ускоряет сборку устройств, перезарядку и смену позиции.",
		"intelligence": "Улучшает схемы, target-logic и маготехнические импульсы.",
		"perception": "Расширяет сетку датчиков, радиус мин и дальность турелей.",
		"energy": "Питает мастерскую, ускоряет ультимейт и длительность активных контуров.",
		"knowledge": "Повышает качество ремонта, DoT-перегрев и стабильность устройств.",
		"endurance": "Дает запас прочности, чтобы успеть развернуть устройства под давлением.",
		"leadership": "Главный стат: повышает лимит/частоту устройств и протоколы поддержки.",
		"magic_damage": "Работает как руническая схема внутри механизмов.",
		"sound_wave_damage": "Работает как сирена мастерской: ближний контроль толпы.",
		"dot_damage": "Добавляет перегрев, искрение и шрапнель к устройствам.",
		"summon_amount": "Усиливает количество активных инженерных устройств и эхо-сборок.",
	},
	"dark_mage": {
		"strength": "Придает вес снарядам: больше knockback и физическая устойчивость.",
		"leadership": "Усиливает фамильярные эхо-касты и поддержку.",
		"sound_wave_damage": "Проявляется как разломный клич, отталкивающий ближайших врагов.",
		"summon_amount": "Учащает вспомогательные эхо-срабатывания.",
	},
	"guitarist": {
		"strength": "Делает волны тяжелее и сильнее отталкивает.",
		"intelligence": "Добавляет магический резонанс к звуку.",
		"dot_damage": "Добавляет жгучий feedback-DoT.",
		"summon_amount": "Увеличивает сценические deploy/echo-срабатывания.",
	},
	"assassin": {
		"intelligence": "Зачаровывает лезвия фиолетовой искрой по области.",
		"sound_wave_damage": "Дает тихий боевой клич-рывок контроля вокруг себя.",
		"leadership": "Фантом-двойник периодически повторяет удар.",
		"summon_amount": "Повышает частоту фантомного повторного удара.",
	},
	"ranger": {
		"intelligence": "Зачаровывает болты магическим splash.",
		"energy": "Быстрее заряжает стойку охотника.",
		"sound_wave_damage": "Боевой окрик отталкивает врагов, если подпустили близко.",
		"leadership": "Сокол-метка периодически повторяет урон по цели.",
	},
	"doctor": {
		"strength": "Утяжеляет инструменты и повышает контроль ближней пилы.",
		"sound_wave_damage": "Командный окрик раздвигает толпу вокруг пациента.",
		"leadership": "Санитарная команда усиливает эхо-лечение/повтор ударов.",
	},
	"chemist": {
		"strength": "Утяжеляет колбы и повышает knockback.",
		"sound_wave_damage": "Хлопок реагентов отталкивает врагов рядом.",
		"leadership": "Автономный помощник/эхо-реакция чаще повторяет удар.",
	},
	"knight": {
		"intelligence": "Зачаровывает сталь магическим splash.",
		"energy": "Сокращает cooldown контратаки.",
		"sound_wave_damage": "Боевой клич щита отталкивает врагов вокруг.",
		"leadership": "Знаменосец-аура чаще вызывает эхо-контроль.",
	},
	"druid": {
		"strength": "Усиливает когти/тернии и knockback.",
		"magic_damage": "Подпитывает природные заклинания и зачарованные зоны.",
		"sound_wave_damage": "Зов стаи работает как контрольная волна.",
		"energy": "Ускоряет природные циклы и уникальные cooldown.",
	},
}

const ATTRIBUTE_PRIORITIES := {
	"berserk": ["strength", "endurance", "agility", "perception", "leadership"],
	"soldier": ["perception", "strength", "agility", "endurance", "leadership"],
	"thief": ["agility", "perception", "strength", "energy", "leadership"],
	"elementalist": ["intelligence", "energy", "perception", "knowledge", "leadership"],
	"sniper": ["perception", "agility", "strength", "endurance", "knowledge"],
	"priest": ["knowledge", "intelligence", "energy", "leadership", "endurance"],
	"biologist": ["knowledge", "intelligence", "perception", "energy", "agility"],
	"robot": ["endurance", "strength", "energy", "perception", "knowledge"],
	"engineer": ["leadership", "intelligence", "perception", "energy", "knowledge"],
	"dark_mage": ["intelligence", "energy", "knowledge", "perception", "leadership"],
	"guitarist": ["leadership", "perception", "energy", "agility", "knowledge"],
	"assassin": ["agility", "strength", "perception", "energy", "leadership"],
	"ranger": ["perception", "agility", "strength", "knowledge", "energy"],
	"doctor": ["knowledge", "intelligence", "energy", "endurance", "perception"],
	"chemist": ["intelligence", "knowledge", "energy", "perception", "agility"],
	"knight": ["endurance", "strength", "leadership", "knowledge", "agility"],
	"druid": ["leadership", "perception", "energy", "knowledge", "endurance"],
}

const ATTRIBUTE_PRIORITY_REASONS := {
	"strength": "усиливает физический урон, контроль оружия и классовые физические интерпретации",
	"agility": "ускоряет атаки и движение, повышает критический шанс и уворот",
	"intelligence": "усиливает магический урон, зачарования и магические классовые механики",
	"perception": "увеличивает дальность, радиусы, pickup и точность позиционирования",
	"energy": "ускоряет уникальные механики, ультимейт и магический/звуковой темп",
	"knowledge": "усиливает DoT, лечение, регенерацию и стабильность билда",
	"endurance": "дает HP, защиту, поглощение и устойчивость под давлением",
	"leadership": "усиливает призывы, эхо-оружие, поддержку и ауры",
}

# SCRUM-695: КАНОНИЧЕСКИЙ реестр боевых атрибутов — единственный источник правды для
# набора прокачиваемых атрибутов (id, RU-имя, иконка-папка, тип значения). Раньше
# список фактически дублировался в трёх местах (папки иконок, LEVEL_UP_REWARDS и
# маппинг reward_attribute_dependency). Теперь LEVEL_UP_REWARDS ссылается на эти id
# через поле "attr", а матрица релевантности ниже строится по этим же id.
#   value_type: "percent" — множитель/доля, "flat" — плоская добавка.
#   icon — имя папки в docs/design/references/icons/attributes/ (трассируемость арта).
const ATTRIBUTE_REGISTRY := [
	{"id": "damage", "name": "Урон", "icon": "damage", "value_type": "percent"},
	{"id": "attack_speed", "name": "Скорость атаки", "icon": "attack_speed", "value_type": "percent"},
	{"id": "max_health", "name": "Макс. здоровье", "icon": "health_point", "value_type": "flat"},
	{"id": "move_speed", "name": "Скорость движения", "icon": "move_speed", "value_type": "percent"},
	{"id": "aoe_radius", "name": "Ширина сектора", "icon": "aoe_radius", "value_type": "percent"},
	{"id": "pickup_radius", "name": "Радиус подбора", "icon": "pickup_radius", "value_type": "flat"},
	{"id": "defense", "name": "Защита", "icon": "defense", "value_type": "percent"},
	{"id": "magic_focus", "name": "Магический фокус", "icon": "magic_damage", "value_type": "percent"},
	{"id": "knockback", "name": "Отталкивание", "icon": "knockback_power", "value_type": "percent"},
	{"id": "crit_chance", "name": "Шанс крита", "icon": "crit_chance", "value_type": "percent"},
	{"id": "crit_damage", "name": "Урон крита", "icon": "crit_damage_multiplier", "value_type": "percent"},
	{"id": "dodge", "name": "Уклонение", "icon": "dodge", "value_type": "percent"},
	{"id": "range", "name": "Дальность атаки", "icon": "attack_range", "value_type": "percent"},
	{"id": "dot_damage", "name": "Периодический урон", "icon": "dot_damage", "value_type": "flat"},
	{"id": "dot_speed", "name": "Скорость тиков", "icon": "dot_speed", "value_type": "flat"},
	{"id": "projectile_speed", "name": "Скорость снарядов", "icon": "projectile_speed", "value_type": "flat"},
	{"id": "aura_radius", "name": "Радиус", "icon": "aura_radius", "value_type": "percent"},
	{"id": "buff_power", "name": "Сила поддержки", "icon": "buff_power", "value_type": "percent"},
	{"id": "summon_amount", "name": "Сила призыва", "icon": "summon_amount", "value_type": "flat"},
	{"id": "absorb", "name": "Поглощение", "icon": "absorb", "value_type": "flat"},
	{"id": "regeneration", "name": "Регенерация", "icon": "regeneration", "value_type": "flat"},
	{"id": "vampiric_amount", "name": "Вампиризм (лечение)", "icon": "vampiric_amount", "value_type": "flat"},
	{"id": "vampiric_chance", "name": "Вампиризм (шанс)", "icon": "vampiric_chance", "value_type": "percent"},
	{"id": "ultimate_power", "name": "Сила ультимейта", "icon": "ultimate_multiplier", "value_type": "percent"},
]

# SCRUM-695: ПРЯМАЯ матрица релевантности (атрибут × 17 классов), первоисточник
# полезности атрибута для класса (заменяет косвенный расчёт через 8 базовых
# характеристик в level-up-наградах). ЖЁСТКИЙ ИНВАРИАНТ по каждому атрибуту:
# ровно 2 primary + 8 secondary + 7 optional = 17 классов (проверяется
# tests/attribute_relevance_test.gd). optional выводится как «все остальные».
# primary = сигнатурный геймплей класса; secondary = ощутимо полезно; optional =
# профильно мимо. Раскладка осмысленна (берсерк — урон/отталкивание/вампиризм,
# снайпер — крит/дальность, жрец — защита/аура/поддержка, друид — аура/призыв/реген).
const ATTRIBUTE_RELEVANCE := {
	"damage": {"primary": ["berserk", "soldier"], "secondary": ["thief", "elementalist", "sniper", "dark_mage", "assassin", "ranger", "chemist", "knight"]},
	"attack_speed": {"primary": ["guitarist", "soldier"], "secondary": ["thief", "elementalist", "sniper", "dark_mage", "assassin", "ranger", "doctor", "chemist"]},
	"max_health": {"primary": ["knight", "robot"], "secondary": ["berserk", "thief", "sniper", "priest", "engineer", "assassin", "ranger", "doctor"]},
	"move_speed": {"primary": ["thief", "ranger"], "secondary": ["berserk", "elementalist", "sniper", "biologist", "dark_mage", "assassin", "chemist", "knight"]},
	"aoe_radius": {"primary": ["elementalist", "chemist"], "secondary": ["berserk", "thief", "sniper", "priest", "robot", "engineer", "dark_mage", "ranger"]},
	"pickup_radius": {"primary": ["robot", "engineer"], "secondary": ["berserk", "thief", "elementalist", "sniper", "assassin", "ranger", "chemist", "knight"]},
	"defense": {"primary": ["knight", "priest"], "secondary": ["thief", "elementalist", "sniper", "engineer", "assassin", "ranger", "doctor", "chemist"]},
	"magic_focus": {"primary": ["dark_mage", "elementalist"], "secondary": ["sniper", "priest", "robot", "engineer", "assassin", "ranger", "doctor", "chemist"]},
	"knockback": {"primary": ["berserk", "guitarist"], "secondary": ["soldier", "elementalist", "sniper", "priest", "biologist", "chemist", "knight", "druid"]},
	"crit_chance": {"primary": ["thief", "sniper"], "secondary": ["berserk", "soldier", "biologist", "robot", "dark_mage", "assassin", "ranger", "druid"]},
	"crit_damage": {"primary": ["sniper", "assassin"], "secondary": ["berserk", "soldier", "thief", "robot", "dark_mage", "guitarist", "ranger", "druid"]},
	"dodge": {"primary": ["thief", "assassin"], "secondary": ["berserk", "soldier", "sniper", "biologist", "guitarist", "ranger", "doctor", "druid"]},
	"range": {"primary": ["sniper", "ranger"], "secondary": ["soldier", "elementalist", "priest", "biologist", "engineer", "dark_mage", "chemist", "druid"]},
	"dot_damage": {"primary": ["biologist", "dark_mage"], "secondary": ["elementalist", "priest", "engineer", "guitarist", "assassin", "doctor", "chemist", "druid"]},
	"dot_speed": {"primary": ["biologist", "chemist"], "secondary": ["elementalist", "priest", "engineer", "dark_mage", "guitarist", "assassin", "doctor", "druid"]},
	"projectile_speed": {"primary": ["soldier", "ranger"], "secondary": ["thief", "elementalist", "sniper", "robot", "engineer", "dark_mage", "guitarist", "chemist"]},
	"aura_radius": {"primary": ["priest", "druid"], "secondary": ["berserk", "soldier", "biologist", "robot", "engineer", "guitarist", "doctor", "knight"]},
	"buff_power": {"primary": ["priest", "engineer"], "secondary": ["berserk", "soldier", "biologist", "robot", "guitarist", "doctor", "knight", "druid"]},
	"summon_amount": {"primary": ["engineer", "druid"], "secondary": ["elementalist", "priest", "biologist", "robot", "dark_mage", "guitarist", "doctor", "knight"]},
	"absorb": {"primary": ["knight", "robot"], "secondary": ["berserk", "soldier", "priest", "biologist", "engineer", "guitarist", "doctor", "druid"]},
	"regeneration": {"primary": ["doctor", "druid"], "secondary": ["berserk", "soldier", "priest", "biologist", "robot", "engineer", "guitarist", "knight"]},
	"vampiric_amount": {"primary": ["berserk", "doctor"], "secondary": ["soldier", "thief", "biologist", "robot", "guitarist", "assassin", "knight", "druid"]},
	"vampiric_chance": {"primary": ["assassin", "doctor"], "secondary": ["berserk", "soldier", "thief", "biologist", "robot", "guitarist", "knight", "druid"]},
	"ultimate_power": {"primary": ["elementalist", "guitarist"], "secondary": ["berserk", "soldier", "priest", "robot", "engineer", "dark_mage", "doctor", "druid"]},
}
