extends RefCounted

# SCRUM-198: character, stat and class identity data. ProgressionData keeps compatibility aliases.

const STAT_NAMES := {
	"strength": "Сила",
	"agility": "Ловкость",
	"intelligence": "Интеллект",
	"perception": "Восприятие",
	"energy": "Энергия",
	"knowledge": "Знание",
	"endurance": "Выносливость",
	"leadership": "Лидерство",
}

const BASE_STATS := {
	"berserk": {
		"strength": 10.0,
		"agility": 5.0,
		"intelligence": 2.0,
		"perception": 5.0,
		"energy": 4.0,
		"knowledge": 4.0,
		"endurance": 7.0,
		"leadership": 3.0,
	},
	"soldier": {
		"strength": 7.0,
		"agility": 6.0,
		"intelligence": 2.0,
		"perception": 8.0,
		"energy": 4.0,
		"knowledge": 5.0,
		"endurance": 6.0,
		"leadership": 5.0,
	},
	"thief": {
		"strength": 5.0,
		"agility": 9.0,
		"intelligence": 3.0,
		"perception": 8.0,
		"energy": 5.0,
		"knowledge": 4.0,
		"endurance": 4.0,
		"leadership": 5.0,
	},
	"elementalist": {
		"strength": 2.0,
		"agility": 4.0,
		"intelligence": 9.0,
		"perception": 7.0,
		"energy": 8.0,
		"knowledge": 6.0,
		"endurance": 3.0,
		"leadership": 5.0,
	},
	"sniper": {
		"strength": 6.0,
		"agility": 8.0,
		"intelligence": 2.0,
		"perception": 10.0,
		"energy": 3.0,
		"knowledge": 3.0,
		"endurance": 7.0,
		"leadership": 1.0,
	},
	"priest": {
		"strength": 2.0,
		"agility": 4.0,
		"intelligence": 8.0,
		"perception": 6.0,
		"energy": 7.0,
		"knowledge": 9.0,
		"endurance": 5.0,
		"leadership": 6.0,
	},
	"biologist": {
		"strength": 2.0,
		"agility": 5.0,
		"intelligence": 8.0,
		"perception": 7.0,
		"energy": 6.0,
		"knowledge": 10.0,
		"endurance": 4.0,
		"leadership": 4.0,
	},
	"robot": {
		"strength": 8.0,
		"agility": 3.0,
		"intelligence": 5.0,
		"perception": 5.0,
		"energy": 7.0,
		"knowledge": 4.0,
		"endurance": 10.0,
		"leadership": 4.0,
	},
	"engineer": {
		"strength": 4.0,
		"agility": 5.0,
		"intelligence": 7.0,
		"perception": 6.0,
		"energy": 6.0,
		"knowledge": 6.0,
		"endurance": 5.0,
		"leadership": 10.0,
	},
	"dark_mage": {
		"strength": 2.0,
		"agility": 3.0,
		"intelligence": 10.0,
		"perception": 5.0,
		"energy": 7.0,
		"knowledge": 6.0,
		"endurance": 2.0,
		"leadership": 5.0,
	},
	"guitarist": {
		"strength": 4.0,
		"agility": 6.0,
		"intelligence": 4.0,
		"perception": 7.0,
		"energy": 6.0,
		"knowledge": 5.0,
		"endurance": 4.0,
		"leadership": 7.0,
	},
	"assassin": {"strength": 6.0, "agility": 10.0, "intelligence": 2.0, "perception": 6.0, "energy": 3.0, "knowledge": 4.0, "endurance": 5.0, "leadership": 4.0},
	"ranger": {"strength": 7.0, "agility": 7.0, "intelligence": 2.0, "perception": 9.0, "energy": 4.0, "knowledge": 4.0, "endurance": 4.0, "leadership": 3.0},
	"doctor": {"strength": 2.0, "agility": 4.0, "intelligence": 8.0, "perception": 5.0, "energy": 6.0, "knowledge": 8.0, "endurance": 5.0, "leadership": 2.0},
	"chemist": {"strength": 2.0, "agility": 4.0, "intelligence": 9.0, "perception": 6.0, "energy": 7.0, "knowledge": 7.0, "endurance": 3.0, "leadership": 2.0},
	"knight": {"strength": 8.0, "agility": 3.0, "intelligence": 2.0, "perception": 4.0, "energy": 3.0, "knowledge": 4.0, "endurance": 10.0, "leadership": 6.0},
	"druid": {"strength": 3.0, "agility": 4.0, "intelligence": 4.0, "perception": 7.0, "energy": 6.0, "knowledge": 5.0, "endurance": 5.0, "leadership": 9.0},
}

const CHARACTER_CONFIGS := {
	"berserk": {
		"id": "berserk",
		"title": "Берсерк",
		"description": "Ближний бой по области и высокий риск.",
		"strengths": "урон, здоровье, толпа.",
		"weaknesses": "нужна близость.",
		"sprite_path": "res://assets/sprites/characters/berserk_unarmed.png",
	},
	"soldier": {
		"id": "soldier",
		"title": "Солдат",
		"description": "Тактика, залпы и контроль позиции.",
		"strengths": "дальность, стабильность, контроль.",
		"weaknesses": "нужна линия огня.",
		"sprite_path": "res://assets/sprites/characters/soldier.png",
	},
	"thief": {
		"id": "thief",
		"title": "Вор",
		"description": "Уловки, рывки и карманная экономика.",
		"strengths": "мобильность, крит, золото.",
		"weaknesses": "мало здоровья.",
		"sprite_path": "res://assets/sprites/characters/thief.png",
	},
	"elementalist": {
		"id": "elementalist",
		"title": "Элементалист",
		"description": "Смена стихий, орбиты и разломы.",
		"strengths": "области поражения, контроль зон, взрывной урон.",
		"weaknesses": "хрупкий, требует позицию.",
		"sprite_path": "res://assets/sprites/characters/elementalist.png",
	},
	"sniper": {
		"id": "sniper",
		"title": "Снайпер",
		"description": "Точные выстрелы, метки и зоны поражения.",
		"strengths": "дальность, одиночные цели, фокус элиток.",
		"weaknesses": "слабее против плотной толпы рядом.",
		"sprite_path": "res://assets/sprites/characters/sniper.png",
	},
	"priest": {
		"id": "priest",
		"title": "Священник",
		"description": "Благословения, печати и священное восстановление.",
		"strengths": "лечение, защита, стабильность.",
		"weaknesses": "меньше взрывного урона по одиночной цели.",
		"sprite_path": "res://assets/sprites/characters/priest.png",
	},
	"biologist": {
		"id": "biologist",
		"title": "Биолог",
		"description": "Образцы, споры и симбиотические реакции.",
		"strengths": "контроль биомассой, периодический урон, адаптация.",
		"weaknesses": "нужны цели для цепных реакций.",
		"sprite_path": "res://assets/sprites/characters/biologist.png",
	},
	"robot": {
		"id": "robot",
		"title": "Робот",
		"description": "Тяжелая броня, магнитный контроль и реакторные выбросы.",
		"strengths": "выживаемость, контроль, стабильный урон.",
		"weaknesses": "медленный, зависит от позиционирования.",
		"sprite_path": "res://assets/sprites/characters/robot.png",
	},
	"engineer": {
		"id": "engineer",
		"title": "Инженер",
		"description": "Мастерская устройств, дронов и минных сеток.",
		"strengths": "устройства, зона контроля, поддержка.",
		"weaknesses": "нужно заранее ставить позицию.",
		"sprite_path": "res://assets/sprites/characters/engineer.png",
	},
	"dark_mage": {
		"id": "dark_mage",
		"title": "Темный маг",
		"description": "Области поражения, лучи и проклятия.",
		"strengths": "площадь, периодический урон, пробивание.",
		"weaknesses": "хрупкий.",
		"sprite_path": "res://assets/sprites/characters/dark_mage.png",
	},
	"guitarist": {
		"id": "guitarist",
		"title": "Гитарист",
		"description": "Ритм, волны и контроль.",
		"strengths": "отталкивание, области поражения, темп.",
		"weaknesses": "слабее по боссам.",
		"sprite_path": "res://assets/sprites/characters/guitarist.png",
	},
	"assassin": {
		"id": "assassin", "title": "Ассасин",
		"description": "Криты, скорость и яд.",
		"strengths": "криты, уворот, темп.",
		"weaknesses": "мало здоровья.",
		"sprite_path": "res://assets/sprites/characters/assassin.png",
	},
	"ranger": {
		"id": "ranger", "title": "Рейнджер",
		"description": "Дальние линии и ловушки.",
		"strengths": "дальность, пробивание.",
		"weaknesses": "плох вблизи.",
		"sprite_path": "res://assets/sprites/characters/ranger.png",
	},
	"doctor": {
		"id": "doctor", "title": "Доктор",
		"description": "Лечение через урон.",
		"strengths": "восстановление, яд, стабильность.",
		"weaknesses": "низкий взрывной урон.",
		"sprite_path": "res://assets/sprites/characters/doctor.png",
	},
	"chemist": {
		"id": "chemist", "title": "Химик",
		"description": "Взрывы и ядовитые зоны.",
		"strengths": "зоны, периодический урон, области поражения.",
		"weaknesses": "хрупкий.",
		"sprite_path": "res://assets/sprites/characters/chemist.png",
	},
	"knight": {
		"id": "knight", "title": "Рыцарь",
		"description": "Танк, копье и щит.",
		"strengths": "здоровье, защита, контроль.",
		"weaknesses": "медленный.",
		"sprite_path": "res://assets/sprites/characters/knight.png",
	},
	"druid": {
		"id": "druid", "title": "Друид",
		"description": "Стая, тернии и тотемы.",
		"strengths": "призывы, зоны.",
		"weaknesses": "слаб один.",
		"sprite_path": "res://assets/sprites/characters/druid.png",
	},
}

const ULTIMATE_CONFIGS := {
	"berserk": {"title": "Неистовство", "description": "На несколько секунд ускоряется и каждый удар поднимает эхо-волну.", "duration": 5.5, "radius": 180.0, "damage": 0.75, "damage_charge_rate": 0.030, "taken_charge_rate": 1.35, "boss_cap": 0.10},
	"soldier": {"title": "Приказ: Огонь", "description": "Серия прицельных залпов по ближайшим целям; сильнее по плотной толпе, но ограничена по боссу.", "duration": 0.0, "radius": 560.0, "damage": 1.08, "target_count": 9, "damage_charge_rate": 0.033, "taken_charge_rate": 1.12, "boss_cap": 0.09},
	"thief": {"title": "Большой Куш", "description": "Мгновенный налет по ближайшим целям: урон, золотые нити и небольшой денежный выигрыш.", "duration": 0.0, "radius": 500.0, "damage": 1.02, "target_count": 8, "damage_charge_rate": 0.036, "taken_charge_rate": 1.00, "boss_cap": 0.08},
	"elementalist": {"title": "Стихийная Сверхнова", "description": "Сверхнова четырех стихий взрывается вокруг героя и оставляет вторичные вспышки по ближайшим целям.", "duration": 0.0, "radius": 430.0, "damage": 1.18, "target_count": 6, "damage_charge_rate": 0.035, "taken_charge_rate": 1.04, "boss_cap": 0.10},
	"sniper": {"title": "Последний Выстрел", "description": "Снайпер отмечает опасные цели и выпускает серию смертельных дальних попаданий.", "duration": 0.0, "radius": 760.0, "damage": 1.35, "target_count": 5, "damage_charge_rate": 0.034, "taken_charge_rate": 0.95, "boss_cap": 0.10},
	"priest": {"title": "Хор Искупления", "description": "Священная волна поражает врагов вокруг и превращает часть урона в лечение.", "duration": 0.0, "radius": 410.0, "damage": 1.05, "target_count": 8, "heal_ratio": 0.45, "damage_charge_rate": 0.031, "taken_charge_rate": 1.22, "boss_cap": 0.08},
	"biologist": {"title": "Пробуждение Колонии", "description": "Биолог запускает рост живой колонии: несколько биоимпульсов поражают ближайших врагов и оставляют слабый реген.", "duration": 0.0, "radius": 440.0, "damage": 1.10, "target_count": 9, "heal_ratio": 0.18, "damage_charge_rate": 0.033, "taken_charge_rate": 1.05, "boss_cap": 0.09},
	"robot": {"title": "Аварийная Перегрузка", "description": "Робот включает аварийный контур: получает временное поглощение, выпускает ударную волну и несколько раз прожигает ближайших врагов.", "duration": 4.5, "radius": 380.0, "damage": 0.78, "target_count": 8, "damage_charge_rate": 0.030, "taken_charge_rate": 1.55, "boss_cap": 0.08},
	"engineer": {"title": "Аварийная Мастерская", "description": "Инженер быстро разворачивает временную сеть устройств: лучи, ремонт и взрывные узлы вокруг себя.", "duration": 4.2, "radius": 430.0, "damage": 0.92, "target_count": 9, "heal_ratio": 0.12, "damage_charge_rate": 0.031, "taken_charge_rate": 1.18, "boss_cap": 0.08},
	"dark_mage": {"title": "Темная буря", "description": "Вихрь темной магии проклинает всех врагов вокруг.", "duration": 0.0, "radius": 360.0, "damage": 1.35, "damage_charge_rate": 0.034, "taken_charge_rate": 1.05, "boss_cap": 0.11},
	"guitarist": {"title": "Соло", "description": "Гигантская звуковая волна отбрасывает и глушит толпу.", "duration": 0.0, "radius": 430.0, "damage": 1.15, "damage_charge_rate": 0.033, "taken_charge_rate": 1.10, "boss_cap": 0.09},
	"assassin": {"title": "Танец клинков", "description": "Серия мгновенных рывков-ударов по ближайшим целям.", "duration": 0.0, "radius": 520.0, "damage": 1.05, "target_count": 7, "damage_charge_rate": 0.036, "taken_charge_rate": 1.05, "boss_cap": 0.08},
	"ranger": {"title": "Лунный залп", "description": "Дождь болтов поражает большую область вокруг героя.", "duration": 0.0, "radius": 480.0, "damage": 1.18, "target_count": 14, "damage_charge_rate": 0.034, "taken_charge_rate": 1.0, "boss_cap": 0.09},
	"doctor": {"title": "Переливание", "description": "Массовый drain врагов вокруг; избыток лечения становится щитом-поглощением.", "duration": 0.0, "radius": 360.0, "damage": 0.95, "damage_charge_rate": 0.032, "taken_charge_rate": 1.25, "boss_cap": 0.08},
	"chemist": {"title": "Цепная реакция", "description": "Алхимический каскад детонирует ближайшие зоны и врагов.", "duration": 0.0, "radius": 420.0, "damage": 1.25, "damage_charge_rate": 0.034, "taken_charge_rate": 1.05, "boss_cap": 0.10},
	"knight": {"title": "Бастион", "description": "Короткая непробиваемость, таунт давления и усиленная контратака.", "duration": 5.0, "radius": 260.0, "damage": 0.70, "damage_charge_rate": 0.029, "taken_charge_rate": 1.55, "boss_cap": 0.07},
	"druid": {"title": "Зов стаи", "description": "Временно призывает сверхлимитную стаю союзников.", "duration": 6.0, "radius": 260.0, "damage": 0.80, "target_count": 4, "damage_charge_rate": 0.031, "taken_charge_rate": 1.10, "boss_cap": 0.08},
}

const CLASS_MECHANIC_IDENTITIES := {
	"berserk": {
		"main_attribute": "strength",
		"identity_title": "Телесный напор",
		"summary": "Сила превращается в тяжелые ближние замахи, контроль толпы и рискованное удержание дистанции рядом с врагами.",
		"mechanic_tags": ["melee_geometry", "frontal_pressure", "crowd_control", "echo_weapon"],
		"weapon_identities": {
			"sword": "длинный направленный frustum-замах для позиционирования",
			"axe": "широкая короткая дуга для чистки толпы рядом",
			"hammer": "центральный AoE slam с сильным ростом от области",
		},
	},
	"soldier": {
		"main_attribute": "perception",
		"identity_title": "Тактическая линия огня",
		"summary": "Восприятие задает линии, дистанции и боевой порядок: солдат выбирает сектор, подавляет толпу и держит позицию.",
		"mechanic_tags": ["line_control", "suppression", "telegraphed_explosive", "brace"],
		"weapon_identities": {
			"soldier_rifle": "подавляющий burst по линии",
			"soldier_grenade": "задержанная граната с читаемой зоной",
			"soldier_bayonet": "оборонительная штыковая стойка",
		},
	},
	"thief": {
		"main_attribute": "agility",
		"identity_title": "Уловка и темп",
		"summary": "Ловкость дает быстрые решения: рикошеты, backstab-окна, дым и экономические трюки вместо прямой силы.",
		"mechanic_tags": ["mobility", "ricochet", "backstab", "smoke_evasion"],
		"weapon_identities": {
			"thief_coin_pouch": "золотой рикошет по нескольким целям",
			"thief_shadow_cloak": "рывок/удар в уязвимое окно",
			"thief_smoke_bomb": "дымовая зона контроля и уклонения",
		},
	},
	"elementalist": {
		"main_attribute": "intelligence",
		"identity_title": "Стихийная формула",
		"summary": "Интеллект собирает разные стихии в контролируемые схемы: орбиты, разломы и метеорные очереди.",
		"mechanic_tags": ["element_cycle", "orbit", "rift", "area_combo"],
		"weapon_identities": {
			"elementalist_orb_ring": "вращающиеся стихийные орбиты",
			"elementalist_prism_focus": "разлом-призма с направленным контролем",
			"elementalist_meteor_core": "осколочный метеорный обстрел",
		},
	},
	"sniper": {
		"main_attribute": "perception",
		"identity_title": "Точная ликвидация",
		"summary": "Восприятие превращает бой в выбор правильной цели: дальность, метки, зоны смерти и пробивающие траектории.",
		"mechanic_tags": ["precision", "marking", "long_range", "kill_zone"],
		"weapon_identities": {
			"sniper_deadeye_rifle": "дальний lockshot по приоритетной цели",
			"sniper_spotter_scope": "зона смерти, наказывающая проходящих врагов",
			"sniper_shatter_rounds": "разделяющийся выстрел по нескольким линиям",
		},
	},
	"priest": {
		"main_attribute": "knowledge",
		"identity_title": "Священная формула",
		"summary": "Знание управляет молитвами, печатями, лечением и наказанием: устойчивый магический sustain вместо взрывного бурста.",
		"mechanic_tags": ["sanctify", "ward", "heal_conversion", "holy_chain"],
		"weapon_identities": {
			"priest_reliquary": "освящение зоны вокруг цели",
			"priest_censer": "ward-пульсы защиты и урона",
			"priest_chime": "цепная молитва между врагами",
		},
	},
	"biologist": {
		"main_attribute": "knowledge",
		"identity_title": "Биореакция",
		"summary": "Знание превращает врагов в материал эксперимента: споры, анализ образцов и симбиотические сети.",
		"mechanic_tags": ["sample_analysis", "spores", "biomass", "adaptive_dot"],
		"weapon_identities": {
			"biologist_spore_lens": "spore bloom зона с тиками",
			"biologist_sample_injector": "sample dart для анализа и фокус-урона",
			"biologist_symbiote_seed": "симбиотическая web-сетка контроля",
		},
	},
	"robot": {
		"main_attribute": "endurance",
		"identity_title": "Бронеконтур",
		"summary": "Выносливость питает тяжелую машину: магнитное удержание, компрессия и реакторные выбросы под давлением.",
		"mechanic_tags": ["armor_loop", "magnet", "compression", "reactor_heat"],
		"weapon_identities": {
			"robot_magnetic_anchor": "магнитный якорь, стягивающий цель",
			"robot_hydraulic_press": "гидравлическая линия компрессии",
			"robot_reactor_core": "реакторная зона перегрева",
		},
	},
	"engineer": {
		"main_attribute": "leadership",
		"identity_title": "Мастерская приказов",
		"summary": "Лидерство управляет устройствами: турельные связи, ремонтные дроны и минные сети работают как команда.",
		"mechanic_tags": ["deployable_network", "device_command", "repair_support", "minefield"],
		"weapon_identities": {
			"engineer_sentry_wrench": "sentry link и фокус турели",
			"engineer_repair_drone": "repair drone с поддержкой",
			"engineer_pressure_mines": "pressure mines для контроля маршрутов",
		},
	},
	"dark_mage": {
		"main_attribute": "intelligence",
		"identity_title": "Темная формула",
		"summary": "Интеллект усиливает проклятия, лучи, взрывы и DoT-зоны: маг контролирует пространство через распад.",
		"mechanic_tags": ["curse", "beam", "dot", "aoe_burst"],
		"weapon_identities": {
			"dark_book": "двойной AoE projectile",
			"cursed_skull": "homing curse с DoT",
			"dark_wand": "двойной pierce beam",
		},
	},
	"guitarist": {
		"main_attribute": "leadership",
		"identity_title": "Сценический контроль",
		"summary": "Лидерство превращает ритм в контроль сцены: волны, пульсы, deploy-усилители и отталкивание.",
		"mechanic_tags": ["rhythm", "knockback", "aura", "deploy_amp"],
		"weapon_identities": {
			"electric_guitar": "направленная звуковая волна",
			"bass_guitar": "частый круговой бас-пульс",
			"sound_amp": "deploy-усилитель с самостоятельными пульсами",
		},
	},
	"assassin": {
		"main_attribute": "agility",
		"identity_title": "Критический танец",
		"summary": "Ловкость дает критовые окна, возвращающиеся клинки, теневые всплески и ядовитые линии без автоперемещения.",
		"mechanic_tags": ["crit_window", "boomerang", "flurry", "poison_line", "shadow_burst"],
		"weapon_identities": {
			"chakrams": "boomerang-коридор туда и обратно",
			"shadow_daggers": "короткая stab flurry серия",
			"venom_wire": "ядовитая pierce-линия",
		},
	},
	"ranger": {
		"main_attribute": "perception",
		"identity_title": "Охотничья стойка",
		"summary": "Восприятие награждает дальность, подготовку и выбор траектории: заряженные выстрелы и ловушки.",
		"mechanic_tags": ["stance_charge", "long_range", "trap", "piercing_shot"],
		"weapon_identities": {
			"moon_crossbow": "заряжаемый одиночный piercing shot",
			"storm_longbow": "веер дальних charged beams",
			"hunter_trap": "deploy trap с burst и knockback",
		},
	},
	"doctor": {
		"main_attribute": "knowledge",
		"identity_title": "Клинический drain",
		"summary": "Знание связывает урон и лечение: доктор выживает через drain-link, чуму и хирургический ближний риск.",
		"mechanic_tags": ["drain_link", "lifesteal", "plague", "surgical_melee"],
		"weapon_identities": {
			"restore_potion": "лечащая drain-связь",
			"plague_syringe": "чумная DoT-связь",
			"bone_saw": "ближняя saw flurry с sustain",
		},
	},
	"chemist": {
		"main_attribute": "intelligence",
		"identity_title": "Алхимическая цепь",
		"summary": "Интеллект комбинирует реагенты: взрывы, кислотные pools и гомункулы создают зоны и цепные реакции.",
		"mechanic_tags": ["cloud_combo", "acid_pool", "explosion", "homunculus"],
		"weapon_identities": {
			"blast_powder": "взрывная пыль и spark cloud",
			"acid_flask": "кислотный DoT pool",
			"homunculus_vial": "temporary homunculus summon",
		},
	},
	"knight": {
		"main_attribute": "endurance",
		"identity_title": "Щитовая клятва",
		"summary": "Выносливость превращается в блок, контратаку и тяжелый контроль: рыцарь держит линию вместо ухода.",
		"mechanic_tags": ["block", "counter", "frontal_control", "tank_pressure"],
		"weapon_identities": {
			"long_spear": "длинный strip-контроль копьем",
			"tower_shield": "shield bash и frontal block",
			"holy_flail": "круговой тяжелый holy control",
		},
	},
	"druid": {
		"main_attribute": "leadership",
		"identity_title": "Командование стаей",
		"summary": "Лидерство управляет зверями и природными зонами: друид дает приказы питомцам, терниям и тотемам.",
		"mechanic_tags": ["commanded_pets", "briar_zone", "totem", "pack_support"],
		"weapon_identities": {
			"summon_amulet": "commanded pet attack target",
			"briar_staff": "терновая зона контроля",
			"raven_totem": "raven/totem support pulses",
		},
	},
}

const CLASS_DAMAGE_PARAMETER := {
	"berserk": "damage",
	"soldier": "damage",
	"thief": "damage",
	"elementalist": "magic_damage",
	"sniper": "damage",
	"priest": "magic_damage",
	"biologist": "magic_damage",
	"robot": "damage",
	"engineer": "damage",
	"dark_mage": "magic_damage",
	"guitarist": "sound_wave_damage",
	"assassin": "damage",
	"ranger": "damage",
	"knight": "damage",
	"doctor": "magic_damage",
	"chemist": "magic_damage",
	"druid": "sound_wave_damage",
}

const STAT_CLASS_RELEVANCE := {}

const CLASS_INTERPRETATIONS := {
	"berserk": {
		"strength": "Прямо усиливает двуручное оружие.",
		"intelligence": "Зачаровывает удары: часть магической силы взрывается искрой вокруг цели.",
		"energy": "Ускоряет темп уникальных срабатываний и усиливает магическое зачарование.",
		"leadership": "Каждые несколько ударов вызывает призрачное эхо-оружие.",
		"magic_damage": "Работает как зачарование физического удара.",
		"sound_wave_damage": "Дает боевой клич: периодическая волна отталкивания вокруг Берсерка.",
		"dot_damage": "Добавляет малое кровотечение к ударам.",
		"summon_amount": "Повышает частоту эхо-оружия.",
	},
	"soldier": {
		"strength": "Усиливает залпы, штык и вес гранат.",
		"intelligence": "Добавляет рунический воспламенитель к гранатам и выстрелам.",
		"energy": "Ускоряет тактические циклы: фитиль, залп и готовность ульты.",
		"knowledge": "Добавляет горение/кровотечение к пораженным целям.",
		"leadership": "Командный клич периодически вызывает эхо-залп строя.",
		"magic_damage": "Работает как зачарованный порох и руническая осколочная искра.",
		"sound_wave_damage": "Работает как команда строя: ближний боевой окрик отталкивает толпу.",
		"dot_damage": "Добавляет малый burn/bleed от пороха и штыка.",
		"summon_amount": "Повышает частоту эхо-залпов и поддержку строя.",
	},
	"thief": {
		"strength": "Добавляет вес backstab-ударам и рикошетам.",
		"agility": "Главный стат: ускоряет темп уловок, крит и выживание через движение.",
		"intelligence": "Зачаровывает дым и монеты теневой искрой.",
		"perception": "Расширяет цепь рикошета, дальность захода и зону дыма.",
		"energy": "Быстрее заряжает Большой Куш и снижает темп провалов.",
		"knowledge": "Добавляет яд/кровотечение к скрытым ударам.",
		"endurance": "Компенсирует низкое HP через устойчивость к ошибкам.",
		"leadership": "Подкупленная тень периодически повторяет удар.",
		"magic_damage": "Работает как теневое зачарование монет и клинков.",
		"sound_wave_damage": "Работает как отвлекающий свист: ближний контроль пространства.",
		"dot_damage": "Добавляет малый яд/bleed к backstab и дыму.",
		"summon_amount": "Учащает подкупленные эхо-удары.",
	},
	"elementalist": {
		"strength": "Утяжеляет метеоры и усиливает knockback от стихийных ударов.",
		"agility": "Ускоряет цикл переключения стихий, движение и шанс крита.",
		"intelligence": "Главный стат: усиливает магический урон всех стихий.",
		"perception": "Расширяет разломы, орбиты и точность выбора зоны.",
		"energy": "Ускоряет заряд Сверхновы и питает длительность стихийных паттернов.",
		"knowledge": "Усиливает burn/frost-like DoT от остаточных вспышек.",
		"endurance": "Компенсирует хрупкость защитой и HP.",
		"leadership": "Фамильяр-искра периодически повторяет малую стихийную вспышку.",
		"damage": "Работает как физический импульс метеорных осколков.",
		"sound_wave_damage": "Работает как громовой хлопок после стихийного удара.",
		"dot_damage": "Добавляет малые burn/frost тики к зонам.",
		"summon_amount": "Учащает фамильярные эхо-вспышки.",
	},
	"sniper": {
		"strength": "Усиливает отдачу тяжелых патронов и knockback lockshot.",
		"agility": "Ускоряет перезарядку, смену позиции и шанс крита.",
		"intelligence": "Зачаровывает патроны малым arcane splash.",
		"perception": "Главный стат: дальность, точность, радиус kill-zone и pickup.",
		"energy": "Быстрее заряжает Последний Выстрел и стабилизирует прицел.",
		"knowledge": "Добавляет bleed/armor-pierce DoT к marked shots.",
		"endurance": "Позволяет пережить ошибку при игре на дистанции.",
		"leadership": "Корректировщик периодически повторяет малый прицельный выстрел.",
		"magic_damage": "Работает как зачарованный наконечник пули.",
		"sound_wave_damage": "Работает как оглушающий дульный хлопок вблизи.",
		"dot_damage": "Добавляет кровотечение к lockshot и split-round.",
		"summon_amount": "Учащает корректировочные эхо-выстрелы.",
	},
	"priest": {
		"strength": "Придает вес кадилу и усиливает knockback священных волн.",
		"agility": "Ускоряет чтение молитв, движение и шанс крита.",
		"intelligence": "Усиливает священный магический урон печатей и молитв.",
		"perception": "Расширяет зоны печатей, дальность реликвария и радиус подбора.",
		"energy": "Быстрее заряжает Хор Искупления и поддерживает частые благословения.",
		"knowledge": "Главный стат: усиливает священные формулы, DoT-покаяние и эффективность лечения.",
		"endurance": "Дает HP/защиту, чтобы удерживать ближнюю ward-зону.",
		"leadership": "Приходская поддержка периодически повторяет малую молитву.",
		"damage": "Работает как физический импульс кадила и реликвария.",
		"sound_wave_damage": "Работает как церковный звон: ближний отталкивающий клич.",
		"dot_damage": "Добавляет покаянное горение к освященным целям.",
		"summon_amount": "Учащает эхо-молитвы прихожан.",
	},
	"biologist": {
		"strength": "Утяжеляет капсулы и повышает knockback биореакций.",
		"agility": "Ускоряет сбор образцов, смену позиции и шанс крита.",
		"intelligence": "Усиливает магическую биохимию спор и симбионтов.",
		"perception": "Расширяет зоны роста, дальность инъектора и радиус подбора.",
		"energy": "Быстрее заряжает Пробуждение Колонии и ускоряет реакционные циклы.",
		"knowledge": "Главный стат: усиливает анализ образцов, DoT и точность биореакций.",
		"endurance": "Компенсирует хрупкость HP/защитой при игре рядом с зонами.",
		"leadership": "Лабораторный ассистент периодически повторяет малую биореакцию.",
		"damage": "Работает как давление капсул и механический импульс инъектора.",
		"sound_wave_damage": "Работает как биоакустический отпугивающий импульс.",
		"dot_damage": "Усиливает споры, инфекционные тики и остаточную биомассу.",
		"summon_amount": "Учащает ассистентские эхо-реакции без добавления отдельного питомца.",
	},
	"robot": {
		"strength": "Главный стат: усиливает сервоприводы, гидравлику и физический импульс оружия.",
		"agility": "Сокращает инерцию корпуса: быстрее перезарядка, движение и шанс крита.",
		"intelligence": "Улучшает боевой алгоритм и добавляет маготехнический splash.",
		"perception": "Расширяет магнитные зоны, дальность захвата и радиус подбора.",
		"energy": "Питает реактор, быстрее заряжает Перегрузку и ускоряет контуры оружия.",
		"knowledge": "Стабилизирует перегрев: усиливает DoT/реген и снижает цену ошибок.",
		"endurance": "Ключевой защитный стат: HP, броня, поглощение и выдержка под давлением.",
		"leadership": "Автопилотный протокол периодически повторяет малый механический импульс.",
		"magic_damage": "Работает как рунический аккумулятор внутри механизма.",
		"sound_wave_damage": "Работает как сирена давления: ближний отталкивающий выброс.",
		"dot_damage": "Добавляет перегрев/искрение к реакторным и прессовым ударам.",
		"summon_amount": "Учащает эхо-протоколы сервоприводов без отдельного питомца.",
	},
	"engineer": {
		"strength": "Усиливает тяжелые инструменты, мины и отдачу турелей.",
		"agility": "Ускоряет сборку устройств, перезарядку и смену позиции.",
		"intelligence": "Улучшает схемы, target-logic и маготехнические импульсы.",
		"perception": "Расширяет сетку датчиков, радиус мин и дальность турелей.",
		"energy": "Питает мастерскую, ускоряет ультимейт и длительность активных контуров.",
		"knowledge": "Повышает качество ремонта, DoT-перегрев и стабильность устройств.",
		"endurance": "Дает запас прочности, чтобы успеть развернуть устройства под давлением.",
		"leadership": "Главный стат: повышает лимит/частоту устройств и протоколы поддержки.",
		"magic_damage": "Работает как руническая схема внутри механизмов.",
		"sound_wave_damage": "Работает как сирена мастерской: ближний контроль толпы.",
		"dot_damage": "Добавляет перегрев, искрение и шрапнель к устройствам.",
		"summon_amount": "Усиливает количество активных инженерных устройств и эхо-сборок.",
	},
	"dark_mage": {
		"strength": "Придает вес снарядам: больше knockback и физическая устойчивость.",
		"leadership": "Усиливает фамильярные эхо-касты и поддержку.",
		"sound_wave_damage": "Проявляется как разломный клич, отталкивающий ближайших врагов.",
		"summon_amount": "Учащает вспомогательные эхо-срабатывания.",
	},
	"guitarist": {
		"strength": "Делает волны тяжелее и сильнее отталкивает.",
		"intelligence": "Добавляет магический резонанс к звуку.",
		"dot_damage": "Добавляет жгучий feedback-DoT.",
		"summon_amount": "Увеличивает сценические deploy/echo-срабатывания.",
	},
	"assassin": {
		"intelligence": "Зачаровывает лезвия фиолетовой искрой по области.",
		"sound_wave_damage": "Дает тихий боевой клич-рывок контроля вокруг себя.",
		"leadership": "Фантом-двойник периодически повторяет удар.",
		"summon_amount": "Повышает частоту фантомного повторного удара.",
	},
	"ranger": {
		"intelligence": "Зачаровывает болты магическим splash.",
		"energy": "Быстрее заряжает стойку охотника.",
		"sound_wave_damage": "Боевой окрик отталкивает врагов, если подпустили близко.",
		"leadership": "Сокол-метка периодически повторяет урон по цели.",
	},
	"doctor": {
		"strength": "Утяжеляет инструменты и повышает контроль ближней пилы.",
		"sound_wave_damage": "Командный окрик раздвигает толпу вокруг пациента.",
		"leadership": "Санитарная команда усиливает эхо-лечение/повтор ударов.",
	},
	"chemist": {
		"strength": "Утяжеляет колбы и повышает knockback.",
		"sound_wave_damage": "Хлопок реагентов отталкивает врагов рядом.",
		"leadership": "Автономный помощник/эхо-реакция чаще повторяет удар.",
	},
	"knight": {
		"intelligence": "Зачаровывает сталь магическим splash.",
		"energy": "Сокращает cooldown контратаки.",
		"sound_wave_damage": "Боевой клич щита отталкивает врагов вокруг.",
		"leadership": "Знаменосец-аура чаще вызывает эхо-контроль.",
	},
	"druid": {
		"strength": "Усиливает когти/тернии и knockback.",
		"magic_damage": "Подпитывает природные заклинания и зачарованные зоны.",
		"sound_wave_damage": "Зов стаи работает как контрольная волна.",
		"energy": "Ускоряет природные циклы и уникальные cooldown.",
	},
}

const ATTRIBUTE_PRIORITIES := {
	"berserk": ["strength", "endurance", "agility", "perception", "leadership"],
	"soldier": ["perception", "strength", "agility", "endurance", "leadership"],
	"thief": ["agility", "perception", "strength", "energy", "leadership"],
	"elementalist": ["intelligence", "energy", "perception", "knowledge", "leadership"],
	"sniper": ["perception", "agility", "strength", "endurance", "knowledge"],
	"priest": ["knowledge", "intelligence", "energy", "leadership", "endurance"],
	"biologist": ["knowledge", "intelligence", "perception", "energy", "agility"],
	"robot": ["endurance", "strength", "energy", "perception", "knowledge"],
	"engineer": ["leadership", "intelligence", "perception", "energy", "knowledge"],
	"dark_mage": ["intelligence", "energy", "knowledge", "perception", "leadership"],
	"guitarist": ["leadership", "perception", "energy", "agility", "knowledge"],
	"assassin": ["agility", "strength", "perception", "energy", "leadership"],
	"ranger": ["perception", "agility", "strength", "knowledge", "energy"],
	"doctor": ["knowledge", "intelligence", "energy", "endurance", "perception"],
	"chemist": ["intelligence", "knowledge", "energy", "perception", "agility"],
	"knight": ["endurance", "strength", "leadership", "knowledge", "agility"],
	"druid": ["leadership", "perception", "energy", "knowledge", "endurance"],
}

const ATTRIBUTE_PRIORITY_REASONS := {
	"strength": "усиливает физический урон, контроль оружия и классовые физические интерпретации",
	"agility": "ускоряет атаки и движение, повышает критический шанс и уворот",
	"intelligence": "усиливает магический урон, зачарования и магические классовые механики",
	"perception": "увеличивает дальность, радиусы, pickup и точность позиционирования",
	"energy": "ускоряет уникальные механики, ультимейт и магический/звуковой темп",
	"knowledge": "усиливает DoT, лечение, регенерацию и стабильность билда",
	"endurance": "дает HP, защиту, поглощение и устойчивость под давлением",
	"leadership": "усиливает призывы, эхо-оружие, поддержку и ауры",
}
