extends SceneTree

const ProgressionData := preload("res://scripts/progression_data.gd")

const REPORT_PATH := "res://build/balance_report.md"


func _init() -> void:
	var report := build_report()
	var absolute_build_dir := ProjectSettings.globalize_path("res://build")
	DirAccess.make_dir_recursive_absolute(absolute_build_dir)
	var file := FileAccess.open(REPORT_PATH, FileAccess.WRITE)
	if file == null:
		push_error("Could not write balance report: %s" % REPORT_PATH)
		quit(1)
		return
	file.store_string(report)
	file.close()
	print("Balance report written: %s" % ProjectSettings.globalize_path(REPORT_PATH))
	quit(0)


static func build_report() -> String:
	var rows := _collect_rows()
	var lines := PackedStringArray()
	lines.append("# FantasyDisk Balance Report")
	lines.append("")
	lines.append("Generated by `tools/balance_harness.gd`.")
	lines.append("")
	lines.append("Window: %.0fs. Targets use `ProgressionData.CLASS_BUDGET_PROFILES`, base solo %.1f DPS and base 5-target %.1f DPS." % [
		ProgressionData.BALANCE_WINDOW_SECONDS,
		ProgressionData.BALANCE_BASE_SOLO_DPS,
		ProgressionData.BALANCE_BASE_AOE_DPS,
	])
	lines.append("")
	lines.append("Formula summary:")
	lines.append("- Solo DPS: expected direct damage, crit factor, post-attack-speed cooldown, DoT/pool/summon contribution and prorated ultimate contribution.")
	lines.append("- 5-target DPS: same formula with deterministic hit-count model per attack mode.")
	lines.append("- EHP: `HP / (1-defense) / (1-dodge) + absorb*10 + regeneration*30 + lifesteal estimate`.")
	lines.append("- Runtime tuning: one `budget_damage_multiplier` per class+weapon is auto-derived from the profile target and applied in `ProgressionData.derived_parameters`; the report also stores solo/5-target residuals so the harness can verify both budget axes without changing attack identity.")
	lines.append("")
	lines.append("## After Tuning")
	lines.append("")
	lines.append(_table(rows, false))
	lines.append("")
	lines.append("## Before Tuning")
	lines.append("")
	lines.append(_table(rows, true))
	lines.append("")
	lines.append("## Profile Summary")
	lines.append("")
	lines.append(_summary(rows))
	lines.append("")
	lines.append("## Enemy Scaling TTK Estimate")
	lines.append("")
	lines.append(_enemy_scaling_ttk_table())
	lines.append("")
	return "\n".join(lines)


static func _collect_rows() -> Array:
	var rows := []
	for character_id in ProgressionData.character_ids():
		var profile: Dictionary = ProgressionData.class_budget_profile(str(character_id))
		for weapon_id in ProgressionData.weapon_ids(str(character_id)):
			var base_weapon: Dictionary = ProgressionData.WEAPONS_BY_CLASS[str(character_id)][str(weapon_id)]
			var tuned_weapon: Dictionary = ProgressionData.weapon(str(character_id), str(weapon_id))
			var before: Dictionary = ProgressionData.estimate_weapon_budget(str(character_id), base_weapon, false)
			var after: Dictionary = ProgressionData.estimate_weapon_budget(str(character_id), tuned_weapon, true)
			var tuning: Dictionary = tuned_weapon.get("budget_tuning", {})
			var solo_target := float(tuning.get("solo_target", ProgressionData.BALANCE_BASE_SOLO_DPS))
			var aoe_target := float(tuning.get("aoe_target", ProgressionData.BALANCE_BASE_AOE_DPS))
			var solo_dev := _deviation(float(after.get("solo_dps", 0.0)), solo_target)
			var aoe_dev := _deviation(float(after.get("aoe_dps", 0.0)), aoe_target)
			var total_dev := _deviation((float(after.get("solo_dps", 0.0)) / solo_target + float(after.get("aoe_dps", 0.0)) / aoe_target) * 0.5, 1.0)
			rows.append({
				"class": str(character_id),
				"weapon": str(weapon_id),
				"profile": str(profile.get("profile", "balanced")),
				"survival": str(profile.get("survival", "steady")),
				"damage_budget": float(profile.get("damage_budget", 1.0)),
				"tuning": float(tuned_weapon.get("budget_damage_multiplier", 1.0)),
				"solo_target": solo_target,
				"aoe_target": aoe_target,
				"before": before,
				"after": after,
				"solo_dev": solo_dev,
				"aoe_dev": aoe_dev,
				"total_dev": total_dev,
			})
	return rows


static func _table(rows: Array, before := false) -> String:
	var lines := PackedStringArray()
	lines.append("| Class | Weapon | Profile | Survival | Tuning | Solo DPS | Solo Target | Solo Dev | 5T DPS | 5T Target | 5T Dev | EHP |")
	lines.append("| --- | --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |")
	for row in rows:
		var metrics: Dictionary = row["before"] if before else row["after"]
		var solo_dev := _deviation(float(metrics.get("solo_dps", 0.0)), float(row["solo_target"]))
		var aoe_dev := _deviation(float(metrics.get("aoe_dps", 0.0)), float(row["aoe_target"]))
		lines.append("| %s | %s | %s | %s | %.3f | %.2f | %.2f | %+.1f%% | %.2f | %.2f | %+.1f%% | %.1f |" % [
			row["class"],
			row["weapon"],
			row["profile"],
			row["survival"],
			float(row["tuning"]) if not before else 1.0,
			float(metrics.get("solo_dps", 0.0)),
			float(row["solo_target"]),
			solo_dev * 100.0,
			float(metrics.get("aoe_dps", 0.0)),
			float(row["aoe_target"]),
			aoe_dev * 100.0,
			float(metrics.get("ehp", 0.0)),
		])
	return "\n".join(lines)


static func _summary(rows: Array) -> String:
	var by_profile := {}
	var max_total_dev := 0.0
	var worst := ""
	for row in rows:
		var profile := str(row["profile"])
		if not by_profile.has(profile):
			by_profile[profile] = {"count": 0, "solo": 0.0, "aoe": 0.0, "ehp": 0.0}
		by_profile[profile]["count"] += 1
		by_profile[profile]["solo"] += float(row["after"].get("solo_dps", 0.0))
		by_profile[profile]["aoe"] += float(row["after"].get("aoe_dps", 0.0))
		by_profile[profile]["ehp"] += float(row["after"].get("ehp", 0.0))
		var total_dev := absf(float(row["total_dev"]))
		if total_dev > max_total_dev:
			max_total_dev = total_dev
			worst = "%s/%s" % [row["class"], row["weapon"]]
	var lines := PackedStringArray()
	lines.append("| Profile | Count | Avg Solo DPS | Avg 5T DPS | Avg EHP |")
	lines.append("| --- | ---: | ---: | ---: | ---: |")
	for profile in by_profile.keys():
		var bucket: Dictionary = by_profile[profile]
		var count := maxf(float(bucket["count"]), 1.0)
		lines.append("| %s | %d | %.2f | %.2f | %.1f |" % [
			profile,
			int(bucket["count"]),
			float(bucket["solo"]) / count,
			float(bucket["aoe"]) / count,
			float(bucket["ehp"]) / count,
		])
	lines.append("")
	lines.append("Max combined budget deviation after tuning: %.1f%% (`%s`)." % [max_total_dev * 100.0, worst])
	return "\n".join(lines)


static func _enemy_scaling_ttk_table() -> String:
	var stages := [0, 2, 4, 6, 8, 10]
	var lines := PackedStringArray()
	lines.append("Budget estimate only; actual encounter time also depends on movement, dodging, pickups, class uptime and route node modifiers.")
	lines.append("")
	lines.append("| Route Stage | Stage Scale | Ordinary Wave TTK | Elite TTK | Boss TTK | Shop Cost x |")
	lines.append("| ---: | ---: | ---: | ---: | ---: | ---: |")
	for stage in stages:
		var scale := ProgressionData.stage_scale(stage)
		var ordinary_wave_ttk := (980.0 * scale) / maxf(ProgressionData.BALANCE_BASE_AOE_DPS, 1.0)
		var elite_ttk := (18.5 * 4.6 * (25.0 + scale * 4.0)) / maxf(ProgressionData.BALANCE_BASE_SOLO_DPS, 1.0)
		var boss_ttk := (350.0 * 1.9 * (4.20 + scale * 1.20)) / maxf(ProgressionData.BALANCE_BASE_SOLO_DPS, 1.0)
		lines.append("| %d | %.3f | %.1fs | %.1fs | %.1fs | %.2fx |" % [
			stage,
			scale,
			ordinary_wave_ttk,
			elite_ttk,
			boss_ttk,
			scale,
		])
	return "\n".join(lines)


static func _deviation(value: float, target: float) -> float:
	if absf(target) <= 0.001:
		return 0.0
	return value / target - 1.0
