extends SceneTree

const ProgressionData := preload("res://scripts/progression_data.gd")

const REPORT_PATH := "res://build/route_economy_xp_model.md"
const START_XP_TO_NEXT := 5
const ATTRIBUTE_BUY_BASE_COST := 18
const ATTRIBUTE_BUY_STAGE_COST := 6
const ATTRIBUTE_REROLL_BASE_COST := 6
const ATTRIBUTE_REROLL_STAGE_COST := 2


func _init() -> void:
	var absolute_build_dir := ProjectSettings.globalize_path("res://build")
	DirAccess.make_dir_recursive_absolute(absolute_build_dir)
	var file := FileAccess.open(REPORT_PATH, FileAccess.WRITE)
	if file == null:
		push_error("Could not write route economy report: %s" % REPORT_PATH)
		quit(1)
		return
	file.store_string(build_report())
	file.close()
	print("Route economy report written: %s" % ProjectSettings.globalize_path(REPORT_PATH))
	quit(0)


static func build_report() -> String:
	var routes := _route_fixtures()
	var rows := []
	for route in routes:
		rows.append(_simulate_route(route))
	var lines := PackedStringArray()
	lines.append("# FantasyDisk Route Economy And XP Model")
	lines.append("")
	lines.append("Generated by `tools/route_economy_xp_model.gd` for SCRUM-188.")
	lines.append("")
	lines.append("This is a deterministic route-level model, not a replacement for live combat telemetry. It uses `ProgressionData.drop_class_rewards()`, `stage_scaled_cost()`, `shop_items()` and the live XP curve so the report follows the current game constants.")
	lines.append("")
	lines.append("## Route Results")
	lines.append("")
	lines.append("| Route | Nodes | Expected XP | Levels | XP Left | Expected Gold | Avg Shop Cost | Affordable Offers | Attr Buys | Rerolls | Buying Power |")
	lines.append("| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |")
	for row in rows:
		lines.append("| %s | %d | %.1f | %d | %d/%d | %.1f | %.1f | %.1f | %.1f | %.1f | %s |" % [
			str(row["title"]),
			int(row["nodes"]),
			float(row["xp"]),
			int(row["levels"]),
			int(row["xp_left"]),
			int(row["xp_to_next"]),
			float(row["gold"]),
			float(row["avg_shop_cost"]),
			float(row["affordable_offers"]),
			float(row["attribute_buys"]),
			float(row["rerolls"]),
			str(row["buying_power"]),
		])
	lines.append("")
	lines.append("## Node Detail")
	lines.append("")
	for row in rows:
		lines.append("### %s" % str(row["title"]))
		lines.append("")
		lines.append("| Step | Node | Stage | XP | Gold | Shop Avg Cost | Note |")
		lines.append("| ---: | --- | ---: | ---: | ---: | ---: | --- |")
		for detail in row["details"]:
			lines.append("| %d | %s | %d | %.1f | %.1f | %.1f | %s |" % [
				int(detail["step"]),
				str(detail["node"]),
				int(detail["stage"]),
				float(detail["xp"]),
				float(detail["gold"]),
				float(detail["avg_shop_cost"]),
				str(detail["note"]),
			])
		lines.append("")
	lines.append("## XP Tempo Decision")
	lines.append("")
	lines.append(_tempo_decision(rows))
	lines.append("")
	lines.append("## Fixture Delta")
	lines.append("")
	lines.append(_fixture_delta())
	lines.append("")
	return "\n".join(lines)


static func _route_fixtures() -> Array:
	return [
		{
			"id": "balanced",
			"title": "Balanced Route",
			"nodes": [
				{"type": "battle", "stage": 0},
				{"type": "battle", "stage": 1},
				{"type": "shop", "stage": 2},
				{"type": "elite", "stage": 2},
				{"type": "battle", "stage": 3},
				{"type": "rest", "stage": 4},
				{"type": "battle", "stage": 5},
				{"type": "upgrade", "stage": 6},
				{"type": "battle", "stage": 7},
				{"type": "boss", "stage": 8},
			],
		},
		{
			"id": "combat_heavy",
			"title": "Combat-Heavy Route",
			"nodes": [
				{"type": "battle", "stage": 0},
				{"type": "battle", "stage": 1},
				{"type": "elite", "stage": 2},
				{"type": "battle", "stage": 3},
				{"type": "battle", "stage": 4},
				{"type": "elite", "stage": 5},
				{"type": "battle", "stage": 6},
				{"type": "shop", "stage": 7},
				{"type": "upgrade", "stage": 8},
				{"type": "battle", "stage": 9},
				{"type": "boss", "stage": 10},
			],
		},
		{
			"id": "shop_heavy",
			"title": "Shop/Rest Route",
			"nodes": [
				{"type": "battle", "stage": 0},
				{"type": "shop", "stage": 1},
				{"type": "battle", "stage": 2},
				{"type": "rest", "stage": 3},
				{"type": "elite", "stage": 4},
				{"type": "shop", "stage": 5},
				{"type": "battle", "stage": 6},
				{"type": "upgrade", "stage": 7},
				{"type": "battle", "stage": 8},
				{"type": "boss", "stage": 9},
			],
		},
	]


static func _simulate_route(route: Dictionary) -> Dictionary:
	var total_xp := 0.0
	var total_gold := 0.0
	var shop_cost_sum := 0.0
	var shop_count := 0
	var attr_cost_sum := 0.0
	var reroll_cost_sum := 0.0
	var details := []
	var step := 0
	for node in route["nodes"]:
		step += 1
		var node_type := str(node["type"])
		var stage := int(node["stage"])
		var node_xp := 0.0
		var node_gold := 0.0
		var note := ""
		if node_type in ["battle", "elite", "boss"]:
			var encounter: Dictionary = _encounter_mix(node_type, stage)
			for drop_class in encounter.keys():
				var rewards: Dictionary = ProgressionData.drop_class_rewards(str(drop_class), stage, 0)
				var count := float(encounter[drop_class])
				node_xp += float(rewards.get("xp", 0)) * count
				node_gold += float(rewards.get("money", 0)) * float(rewards.get("money_chance", 0.0)) * count
			note = _encounter_note(encounter)
		elif node_type == "shop":
			var avg_cost := _average_shop_cost(stage)
			shop_cost_sum += avg_cost
			shop_count += 1
			note = "4 displayed offers sampled from %.1f avg pool cost" % avg_cost
		elif node_type == "rest":
			note = "Rest node: no direct economy payout"
		elif node_type == "upgrade":
			var attr_cost := _attribute_buy_cost(stage)
			var reroll_cost := _attribute_reroll_cost(stage)
			attr_cost_sum += float(attr_cost)
			reroll_cost_sum += float(reroll_cost)
			note = "Attribute buy %d, reroll %d" % [attr_cost, reroll_cost]
		total_xp += node_xp
		total_gold += node_gold
		details.append({
			"step": step,
			"node": node_type,
			"stage": stage,
			"xp": node_xp,
			"gold": node_gold,
			"avg_shop_cost": _average_shop_cost(stage) if node_type == "shop" else 0.0,
			"note": note,
		})
	var xp_state := _level_state(total_xp)
	var avg_shop_cost := shop_cost_sum / maxf(float(shop_count), 1.0)
	var affordable_offers := total_gold / maxf(avg_shop_cost, 1.0)
	var attr_buys := total_gold / maxf(attr_cost_sum, 1.0) if attr_cost_sum > 0.0 else 0.0
	var rerolls := total_gold / maxf(reroll_cost_sum, 1.0) if reroll_cost_sum > 0.0 else 0.0
	return {
		"title": str(route["title"]),
		"nodes": (route["nodes"] as Array).size(),
		"xp": total_xp,
		"gold": total_gold,
		"levels": int(xp_state["levels"]),
		"xp_left": int(xp_state["xp_left"]),
		"xp_to_next": int(xp_state["xp_to_next"]),
		"avg_shop_cost": avg_shop_cost,
		"affordable_offers": affordable_offers,
		"attribute_buys": attr_buys,
		"rerolls": rerolls,
		"buying_power": _buying_power_label(affordable_offers, attr_buys),
		"details": details,
	}


static func _encounter_mix(node_type: String, stage: int) -> Dictionary:
	match node_type:
		"elite":
			return {
				"ordinary": 13.0 + float(stage),
				"complex": 5.0 + floorf(float(stage) * 0.35),
				"heavy": 3.0 + floorf(float(stage) * 0.25),
				"elite": 1.0,
			}
		"boss":
			return {
				"ordinary": 12.0 + float(stage) * 0.5,
				"complex": 4.0,
				"heavy": 2.0,
				"boss": 1.0,
			}
		_:
			return {
				"ordinary": 20.0 + float(stage) * 2.0,
				"complex": 4.0 + floorf(float(stage) * 0.45),
				"heavy": 2.0 + floorf(float(stage) * 0.30),
			}


static func _encounter_note(encounter: Dictionary) -> String:
	var parts := []
	for drop_class in encounter.keys():
		parts.append("%s x%.1f" % [str(drop_class), float(encounter[drop_class])])
	return ", ".join(parts)


static func _level_state(expected_xp: float) -> Dictionary:
	var xp := int(round(expected_xp))
	var xp_to_next := START_XP_TO_NEXT
	var levels := 0
	while xp >= xp_to_next:
		xp -= xp_to_next
		levels += 1
		xp_to_next = ProgressionData.next_xp_requirement(xp_to_next)
	return {"levels": levels, "xp_left": xp, "xp_to_next": xp_to_next}


static func _average_shop_cost(stage: int) -> float:
	var items := ProgressionData.shop_items(stage)
	var total := 0.0
	for item in items:
		total += float((item as Dictionary).get("cost", 0))
	return total / maxf(float(items.size()), 1.0)


static func _attribute_buy_cost(stage: int) -> int:
	return ProgressionData.stage_scaled_cost(ATTRIBUTE_BUY_BASE_COST + ATTRIBUTE_BUY_STAGE_COST * stage, stage)


static func _attribute_reroll_cost(stage: int) -> int:
	return ProgressionData.stage_scaled_cost(ATTRIBUTE_REROLL_BASE_COST + ATTRIBUTE_REROLL_STAGE_COST * stage, stage)


static func _buying_power_label(affordable_offers: float, attr_buys: float) -> String:
	if affordable_offers >= 6.0 and attr_buys >= 2.0:
		return "high"
	if affordable_offers >= 3.5 and attr_buys >= 1.0:
		return "healthy"
	return "tight"


static func _tempo_decision(rows: Array) -> String:
	var level_sum := 0.0
	var min_levels := 999
	var max_levels := 0
	for row in rows:
		var levels := int(row["levels"])
		level_sum += float(levels)
		min_levels = mini(min_levels, levels)
		max_levels = maxi(max_levels, levels)
	var avg_levels := level_sum / maxf(float(rows.size()), 1.0)
	var lines := PackedStringArray()
	lines.append("- Current modeled routes produce %.1f level-ups on average (range %d-%d) before/including the boss reward." % [avg_levels, min_levels, max_levels])
	lines.append("- Buying power is healthy across the representative routes: each route can afford several shop offers or at least one post-fight attribute upgrade window without starving the run.")
	lines.append("- SCRUM-527: XP-кривая перекалибрована (множитель 1.42→1.038, flat 3.0→0.8) так, чтобы средний забег приходил к боссу 1-го акта примерно на 20 lvl (репрезентативные balanced/shop маршруты = 20, combat-heavy = 24). Рост требуемого опыта почти линейный (req ~5→10→20→30→44), без крутого геометрического разгона.")
	return "\n".join(lines)


static func _fixture_delta() -> String:
	var route_stages := [0, 1, 2, 3, 4, 5]
	var encounter_mix := {
		"ordinary": 72,
		"complex": 14,
		"heavy": 10,
		"mini_elite": 2,
		"elite": 1,
	}
	var old_money := 0.0
	var old_xp := 0.0
	var new_money := 0.0
	var new_xp := 0.0
	for stage in route_stages:
		for drop_class in encounter_mix.keys():
			var count := float(encounter_mix[drop_class]) / float(route_stages.size())
			var rewards: Dictionary = ProgressionData.drop_class_rewards(str(drop_class), stage, 0)
			new_xp += float(rewards.get("xp", 0)) * count
			new_money += float(rewards.get("money", 0)) * float(rewards.get("money_chance", 0.75)) * count
			match str(drop_class):
				"complex":
					old_xp += 2.0 * count
					old_money += 1.0 * 0.75 * count
				"heavy":
					old_xp += 3.0 * count
					old_money += 2.0 * 0.75 * count
				"mini_elite":
					old_xp += 4.0 * count
					old_money += 4.0 * count
				"elite":
					old_xp += 8.0 * count
					old_money += 6.0 * count
				_:
					old_xp += 1.0 * count
					old_money += 1.0 * 0.75 * count
	var buying_power_delta := ((new_money / ProgressionData.ECONOMY_PRICE_MULTIPLIER) / maxf(old_money, 0.001) - 1.0) * 100.0
	var xp_delta := (new_xp / maxf(old_xp, 0.001) - 1.0) * 100.0
	var lines := PackedStringArray()
	lines.append("| Metric | Old Fixture | Current Fixture | Delta |")
	lines.append("| --- | ---: | ---: | ---: |")
	lines.append("| Expected gold | %.1f | %.1f | %+0.1f%% |" % [old_money, new_money, (new_money / maxf(old_money, 0.001) - 1.0) * 100.0])
	lines.append("| Effective buying power | %.1f | %.1f | %+0.1f%% |" % [old_money, new_money / ProgressionData.ECONOMY_PRICE_MULTIPLIER, buying_power_delta])
	lines.append("| Expected XP | %.1f | %.1f | %+0.1f%% |" % [old_xp, new_xp, xp_delta])
	lines.append("| XP curve | `ceil(req*1.35+2)` | `ceil(req*%.2f+%.0f)` | guarded |" % [ProgressionData.XP_CURVE_MULTIPLIER, ProgressionData.XP_CURVE_FLAT])
	return "\n".join(lines)
