extends SceneTree

const ProgressionData := preload("res://scripts/progression_data.gd")

const REPORT_PATH := "res://build/survivability_scenarios_report.md"
const WINDOW_SECONDS := 30.0

const SCENARIOS := [
	{"id": "contact_swarm", "title": "Contact Swarm", "incoming_dps": 18.0, "hits_per_second": 2.2, "dodge_weight": 1.0, "regen_window": 30.0},
	{"id": "shooter_crossfire", "title": "Shooter Crossfire", "incoming_dps": 15.0, "hits_per_second": 1.4, "dodge_weight": 1.25, "regen_window": 30.0},
	{"id": "elite_burst", "title": "Elite Burst", "incoming_dps": 34.0, "hits_per_second": 0.7, "dodge_weight": 0.75, "regen_window": 12.0},
	{"id": "boss_phase_hazard", "title": "Boss Phase Hazard", "incoming_dps": 28.0, "hits_per_second": 1.0, "dodge_weight": 0.85, "regen_window": 22.0},
]

const SURVIVAL_TARGETS := {
	"fragile": {"min": 5.0, "max": 18.0},
	"control": {"min": 8.0, "max": 24.0},
	"steady": {"min": 11.0, "max": 32.0},
	"sturdy": {"min": 14.0, "max": 38.0},
	"tank": {"min": 18.0, "max": 55.0},
}


func _init() -> void:
	var absolute_build_dir := ProjectSettings.globalize_path("res://build")
	DirAccess.make_dir_recursive_absolute(absolute_build_dir)
	var file := FileAccess.open(REPORT_PATH, FileAccess.WRITE)
	if file == null:
		push_error("Could not write survivability report: %s" % REPORT_PATH)
		quit(1)
		return
	file.store_string(build_report())
	file.close()
	print("Survivability scenarios report written: %s" % ProjectSettings.globalize_path(REPORT_PATH))
	quit(0)


static func build_report() -> String:
	var rows := _scenario_rows()
	var lines := PackedStringArray()
	lines.append("# FantasyDisk Survivability Scenario Report")
	lines.append("")
	lines.append("Generated by `tools/survivability_scenarios.gd` for SCRUM-255.")
	lines.append("")
	lines.append("This is a deterministic balance harness using current SCRUM-255 survivability formulas.")
	lines.append("")
	lines.append("## Scenario Matrix")
	lines.append("")
	lines.append("| Class | Survival | Scenario | TTD | Expected Band | Result | Health | Defense | Dodge | Absorb | Regen | Lifesteal |")
	lines.append("| --- | --- | --- | ---: | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: |")
	for row in rows:
		lines.append("| %s | %s | %s | %.1fs | %s | %s | %.0f | %.0f | %.0f | %.0f | %.0f | %.0f |" % [
			row["class"],
			row["survival"],
			row["scenario"],
			float(row["ttd"]),
			row["band"],
			row["result"],
			float(row["health"]),
			float(row["defense_value"]),
			float(row["dodge_value"]),
			float(row["absorb_value"]),
			float(row["regen_value"]),
			float(row["lifesteal_value"]),
		])
	lines.append("")
	lines.append("## Summary")
	lines.append("")
	lines.append(_summary(rows))
	lines.append("")
	return "\n".join(lines)


static func _scenario_rows() -> Array:
	var rows := []
	for character_id in ProgressionData.character_ids():
		var profile: Dictionary = ProgressionData.class_budget_profile(character_id)
		var survival := str(profile.get("survival", "steady"))
		var weapon_ids := ProgressionData.weapon_ids(character_id)
		if weapon_ids.is_empty():
			continue
		var weapon: Dictionary = ProgressionData.weapon(character_id, str(weapon_ids[0]))
		var params: Dictionary = ProgressionData.derived_parameters(ProgressionData.base_stats(character_id), {}, weapon)
		for scenario in SCENARIOS:
			rows.append(_simulate_scenario(character_id, survival, params, weapon, scenario))
	return rows


static func _simulate_scenario(character_id: String, survival: String, params: Dictionary, weapon: Dictionary, scenario: Dictionary) -> Dictionary:
	var health := float(params.get("health_point", 1.0))
	var defense := clampf(float(params.get("defense", 0.0)), 0.0, ProgressionData.SURVIVABILITY_DEFENSE_CAP)
	var dodge := clampf(float(params.get("dodge", 0.0)) * float(scenario.get("dodge_weight", 1.0)), 0.0, ProgressionData.SURVIVABILITY_DODGE_CAP)
	var absorb := float(params.get("absorb", 0.0))
	var regen := float(params.get("regeneration", 0.0))
	var lifesteal := _lifesteal_per_second(params, weapon)
	var incoming_dps := float(scenario.get("incoming_dps", 1.0))
	var absorb_dps_offset := absorb * float(scenario.get("hits_per_second", 1.0))
	var after_absorb_dps := maxf(incoming_dps - absorb_dps_offset, incoming_dps * ProgressionData.SURVIVABILITY_ABSORB_MIN_DAMAGE_FRACTION)
	var effective_dps := after_absorb_dps * maxf(1.0 - defense, 0.10) * maxf(1.0 - dodge, 0.10)
	var sustain := regen + lifesteal
	var net_dps := maxf(effective_dps - sustain, 0.01)
	var ttd := health / net_dps
	var band: Dictionary = SURVIVAL_TARGETS.get(survival, SURVIVAL_TARGETS["steady"])
	var min_ttd := float(band.get("min", 0.0))
	var max_ttd := float(band.get("max", 9999.0))
	var result := "ok"
	if ttd < min_ttd:
		result = "low"
	elif ttd > max_ttd:
		result = "high"
	return {
		"class": character_id,
		"survival": survival,
		"scenario": str(scenario["title"]),
		"ttd": snappedf(ttd, 0.1),
		"band": "%.0f-%.0fs" % [min_ttd, max_ttd],
		"result": result,
		"health": health,
		"defense_value": health / maxf(1.0 - defense, 0.05) - health,
		"dodge_value": health / maxf(1.0 - defense, 0.05) / maxf(1.0 - dodge, 0.05) - health / maxf(1.0 - defense, 0.05),
		"absorb_value": maxf(incoming_dps - after_absorb_dps, 0.0) * float(scenario.get("regen_window", WINDOW_SECONDS)),
		"regen_value": regen * float(scenario.get("regen_window", WINDOW_SECONDS)),
		"lifesteal_value": lifesteal * float(scenario.get("regen_window", WINDOW_SECONDS)),
	}


static func _lifesteal_per_second(params: Dictionary, weapon: Dictionary) -> float:
	var chance := clampf(float(params.get("vampiric_chance", 0.0)), 0.0, ProgressionData.VAMPIRIC_CHANCE_CAP)
	var amount := float(params.get("vampiric_amount", 0.0))
	var cap := ProgressionData.VAMPIRIC_HEAL_CAP_DEFAULT
	var interval := maxf(float(weapon.get("fire_interval", 1.0)), 0.18)
	var weapon_drain := (
		float(weapon.get("heal_percent_of_damage", 0.0)) * 55.0
		+ float(weapon.get("heal_percent_on_attack", 0.0)) * float(params.get("health_point", 1.0)) / interval
	) * ProgressionData.WEAPON_DRAIN_HEAL_MULTIPLIER
	return minf(chance * amount / interval + weapon_drain, ProgressionData.effective_vampiric_cap(cap))


static func _summary(rows: Array) -> String:
	var counts := {"ok": 0, "low": 0, "high": 0}
	var by_survival := {}
	for row in rows:
		var result := str(row["result"])
		counts[result] = int(counts.get(result, 0)) + 1
		var survival := str(row["survival"])
		if not by_survival.has(survival):
			by_survival[survival] = {"count": 0, "ttd": 0.0}
		by_survival[survival]["count"] += 1
		by_survival[survival]["ttd"] += float(row["ttd"])
	var lines := PackedStringArray()
	lines.append("- Results: %d ok, %d low, %d high." % [int(counts["ok"]), int(counts["low"]), int(counts["high"])])
	lines.append("- Outliers are report flags for class survivability bands after SCRUM-255 formula changes.")
	lines.append("")
	lines.append("| Survival | Rows | Avg TTD |")
	lines.append("| --- | ---: | ---: |")
	for survival in by_survival.keys():
		var bucket: Dictionary = by_survival[survival]
		lines.append("| %s | %d | %.1fs |" % [
			survival,
			int(bucket["count"]),
			float(bucket["ttd"]) / maxf(float(bucket["count"]), 1.0),
		])
	return "\n".join(lines)
